<!--PAGINA DETALHES DO PEDIDO-->
         <?php 
         $filter = new \NumberFormatter('pt_BR', \NumberFormatter::CURRENCY);
         $offValue = false;
         if($this->cadastro->getRua() && $this->cadastro->getNumero() && $this->cadastro->getBairro() && $this->cadastro->getMapeamentocidade() && $this->cadastro->getMapeamentocidade()->getMapeamentoestado() && $this->cadastro->getCep()) $offValue = true;
         ?>
         <div id="ajaxRecebimento" style="display:none">
         
         </div>
	<div id="PaginaDoUsuario">
			<div id="MenuDoUsuario">
				<ul class="BoxMenuDoUsuario">
					<li class="BoxMenuInstitucional">
						<a href="#meusDados" class="MeusDados" title="Meus Dados">Meus Dados</a>
					</li>
					<li class="BoxMenuInstitucional">
						<a href="#enderecos" class="EndEntrega" title="Endereços de Entregas">Endereços de Entregas</a>
					</li>
					<li class="BoxMenuInstitucional">
						<a href="#pedido" class="SeuPedido" title="Seus Pedidos">Seus Pedidos</a>
					</li>
				</ul>
			</div>

		<div id="BoxPaginaDoUsuario" >

			<!-- CONTEUDO DADOS DO USUARIO-->
			<div id="BoxMeusDados" style="display:none">
				 <div id="MeusDados">
				  <p class="TituloEnderecoResidencial">Meu Cadastro</p>
				   <p class="ttBoxLogin">*Todos os campos são obrigatórios</p><br/>

					<form action="" class="formActionCadastroUsuario">
                            
					 <label class="FormNome">Nome do Destinatário*:</label><br/>
					 <input type="text" class="BoxNome" value="<?=$this->cadastro->getNome()?>"><br/>
					 <p class="xxx">(Nome que deverá ser impresso na nota fiscal)</p><br/>

					 <input type="radio" class="tipoUsuario" name="tipoUsuario"  value="1" <?if($this->cadastro->getTipoUser() == 1) print 'checked';?>>Pessoa Física*:
					 <input type="radio" class="tipoUsuario" name="tipoUsuario"  value="2" <?if($this->cadastro->getTipoUser() == 2) print 'checked';?>>Pessoa Jurídica*:<br/>
					 <input type="text" value="<?if($this->cadastro->getTipoUser() == 1){print $this->cadastro->getCpf();}else{print $this->cadastro->getCnpj();}?>" class="PessoaSeletc"><br/><p class="xxx">(Informe seu CPF ou CNPJ)</p><br/>
					   <div class="showInscEstadual"  <?if($this->cadastro->getTipoUser() == 1) print 'style="display:none"';?>>
					 <label class="FormEstado">Numero da Inscrição Estadual*:</label><br/>
					 <input type="text" class="InscEstadual" value="<?=$this->cadastro->getInscricaoEstadual()?>"><br/><p class="xxx">(Informe o Numero da Inscrição Estadual)</p><br/>
                        </div>
                     <label class="FormTelResidencial">Telefone Residencial*:</label>
                     <label class="FormTelCelular">Telefone Celular:</label>
                              
                     <input type="text" class="BoxTelResidencial" value="<?=$this->cadastro->getTelefoneRes()?>">
				     <input type="text" class="BoxTelCelular" value="<?=$this->cadastro->getTelefoneCel()?>"><br/><br/>
                         <div class="showInscEstadual"  <?if($this->cadastro->getTipoUser() == 1) print 'style="display:none"';?>>
					 <label class="FormTelComercial">Telefone Comercial:</label><br/>
					 <input type="text" class="BoxTelComercial" value="<?=$this->cadastro->getTelefoneCom()?>"><br/><br/>
					     </div>
					 <input type="submit" title="Salvar Cadastro" value="Salvar Cadastro" class="EventSalvarEnderecoPainel">
					     <br/><br/><br/>
                     </form>
					<form action="" class="formActionCadastroUsuario">
                     <p class="AlterarMinhaSenha"><a href="#">Alterar minha Senha:</a></p>
                     	
		                     <label class="FormSenha">Senha Atual:</label><br/>
		                     <input type="text" class="BoxSenha"><br/><br/>

		                     <label class="FormSenha">Nova Senha:</label><br/>
							 <input type="text" class="BoxNovaSenha"><br/><br/>
		           
		                     <label class="FormConfirmarSenha">Confirmar Nova Senha:</label><br/>
		                     <input type="text" class="BoxAlterarSenha"><br/><br/>
		                      <input type="submit" title="Alterar Senha" value="Alterar Senha" class="EventcadastrarCadastro"><br/><br/><br/>
	                </form>
        
					 
					  
					
				 </div>
				
				<div id="MeuEndereco" >
				  <p class="TituloEnderecoResidencial">Meu Endereço</br>
                    <span class="DetalheEnderecoResidencial">Para alterar o endereço informe primeiro o CEP</p>
                      <p class="ttBoxLogin">*Todos os campos são obrigatórios</p></br>
						<form action="" class="formAction">
						    <input type="hidden" value="zzz"/>
					      <label class="FormCEP">CEP*:</label><br/><input type="text" class="BoxCEP" <?if($offValue) print 'disabled="disabled"'?> value="<?=$this->cadastro->getCep()?>"><span class="ajaxMsg" style="color:#ff7f25;display:none;font-weight:bold"></span><br/><br/>
					       <label class="FormEndereco">Endereço*:</label><br/><input type="text" class="BoxEndereco" <?if($offValue) print 'disabled="disabled"'?> value="<?=$this->cadastro->getRua()?>"><br/><p class="xxx">(Deverá ser informado se o endereço é Rua/Avenida/
                                      Quadra/Estrada/Praça e na sequência o nome do endereço)</p><br/>
					         <label class="FormNumero">Numero*:</label>           
                               <br/>
					            <input type="text" class="BoxNumero" <?if($offValue) print 'disabled="disabled"'?> value="<?=$this->cadastro->getNumero()?>">
					             <br/><br/>
					              
					               <label class="FormEstado">Estado*:</label><br/>
					              <select class="BoxEstado" <?if($offValue) print 'disabled="disabled"'?>>
					                  <option value="">Selecione</option>
					                      <?php 
					                          foreach($this->estados AS $estados)
					                          {
					                      ?>
					                      <option value="<?=$estados->getNomeclatura()?>" <?php if($this->cidadeEstadoUF == $estados->getNomeclatura()) print "selected"?>><?=$estados->getNome()?></option>
					                      <?php 
					                          }?>
					                  </select><br/><br/>

					                  <label class="FormBairro">Bairro*:</label>
					               <label class="FormCidade">Cidade*:</label><br/>
					                <input type="text" class="BoxBairro" <?if($offValue) print 'disabled="disabled"'?> value="<?=$this->cadastro->getBairro()?>">
					                <?php
                                            if(count($this->cidades) >= 1)
                                            {
                                                ?>
                                       <select class="BoxCidade" <?if($offValue) print 'disabled="disabled"'?>>
                                          <?php 
                                              foreach($this->cidades AS $cidade)
                                              {
                                          ?>
                                                   <option value="<?=$cidade->getIdcidade()?>" <?php if($this->cidadeSelected == $cidade->getIdcidade()) print "selected"?>><?=$cidade->getNome()?></option>
                                           <?php 
                                              }
                                               ?>
                                       </select>         
                                                <?php 
                                            }
                                            else
                                            {
					                  ?>
					                   <select class="BoxCidade" disabled="disabled"><option value="">Selecione</option></select>
					                   <?php 
                                            }
					                   ?><br/><br/>

					                  <input type="hidden" class="cadastroIdAction" value="<?=$this->cadastro->getIdcadastro()?>"/>
					             <?if($offValue)
				{
				    ?>
				   <div class="seletoInt"><span class="EditarDados" title="Editar Endereço" id="bottaoAlterarCadastro">Editar</span></div> 
					        
					        <?php 
				}
				else
				{
					        ?>
					        <input type="submit" title="Salvar Endereço" value="Salvar Endereço" class="EventsalvarEnderecoPainel">
					        <?php 
				}	        
					        ?>
					        <br/><br/><br/>
					    </form>
				</div>
			</div>

			<!-- FIM DO CONTEUDO DADOS DO USUARIO-->

			<!--ENDEREÇOS DO USUARIO-->
			<div id="BoxMeuEndereco" style="display:none">

				<div id="BoxTitulo">
					<p class="TituloBoxMeuEndereco">Meus Endereços Cadastrados</p>

				    <span class="ButtonNovoEndereco" title="Novo Endereço">Novo Endereço</span></a>
				    
				</div>
				<?if($offValue)
				{
				    ?>
					<table id="EditarEndereco">
						<tr class="BoxRadio">
						<th class="radio"></th>
						<th class="TextoEditarEnd"><?=$this->cadastro->getRua()?> - <?=$this->cadastro->getNumero()?> ,
                                    <?=$this->cadastro->getBairro()?> - <?if($this->cadastro->getMapeamentocidade())
                                    {
                                       print $this->cadastro->getMapeamentocidade()->getNome();
                                    }?> - <?
                                    if($this->cadastro->getMapeamentocidade() && $this->cadastro->getMapeamentocidade()->getMapeamentoestado())
                                    {
                                      print $this->cadastro->getMapeamentocidade()->getMapeamentoestado()->getNomeclatura();
                                    }
                                    
                                    ?> - <?=$this->cadastro->getCep()?></th>

						<th class="bt_excluirVasio"></th>

						<th class="bt_editar"><a href="" rel="<?=$this->cadastro->getIdcadastro()?>" class="openEventEditCadastro" title="Editar endereço de entrega"><img src="<?=$this->basePath()?>/images/icon_editar.png"></a></th>
						</tr>
					</table>
					<?php 
				}
				else
				{
					?>
					   
					        <center>Seu endereço está incompleto, Clique em <a href="" class="MeusDados">Meus Dados</a> para concluír seu cadastro.</center>
					<?php
				}
					?>
                 <?php
                                        foreach($this->cadastrosAlternativos AS $alternativo)
                                        {
                                        	?>
					<table id="EditarEndereco">
						<tr class="BoxRadio">
						<th class="radio"></th>
						<th class="TextoEditarEnd"><?=$alternativo->getRua()?> - <?=$alternativo->getNumero()?> ,
                                    <?=$alternativo->getBairro()?> - <?=$alternativo->getMapeamentocidade()->getNome()?> - <?=$alternativo->getMapeamentocidade()->getMapeamentoestado()->getNomeclatura()?> - <?=$alternativo->getCep()?></th>

						<th class="bt_excluirEditarEnd EventRemoverCadastro" rel="<?=$alternativo->getIdcadastro()?>" title="Excluir endereço de entrega"></th>

						<th class="bt_editar"><a href="" rel="<?=$alternativo->getIdcadastro()?>" class="openEventEditCadastro" title="Editar endereço de entrega"><img src="<?=$this->basePath()?>/images/icon_editar.png"></a></th>
						</tr>
					</table>
					            <?php 
                                        }
					            ?>
			</div>

			<!-- FIM DO ENDEREÇOS DO USUARIO-->    



			<!--PEDIDOS-->
				<div id="BoxDetalheDoPedido" style="display:none">
				<?php 
				    if(count($this->recibos) == 0)
				    {
				    	?>
				    	    <center>Você no momento não tem novos pedidos:</center>
				    	<?php
				    }
				    else 
				    {
				?>
					<p class="txtAvisoPedido">*Clique no número do pedido para mais informações:</p>
					<?php     
					    foreach($this->recibos AS $recibo)
					    {
					?>

						<ul id="DadosDetalheDoPedido">
							 <li class="tt_Pedidos">Número do pedido</li>
							 <li class="tt_Pedidos">Data do pedido</li>
							 <li class="tt_Pedidos">Forma de pagamento</li>
							 <li class="tt_Pedidos">Valor total</li>
						</ul>

						<ul>
							<li class="DadosDoPedido">
								<div id="ContainerDetalheDoPedido">
								 	<p><a class="txt_NumeroDetalhePedido" href="<?=$this->url("Painel-usuario/Painel-usuario-recibo",array("idPedido" => $recibo->getIdcontrolerecibo()*3500));?>" title="Veja o detalhe do seu pedido">000<?=$recibo->getIdcontrolerecibo()?></a></p>
								</div>
								<div id="ContainerDetalheDoPedido">
								 	<p class="txt_DadosDoPedido"><?
								 	print $recibo->getDtVenda()->format("d/m/Y h:m:s");
						?></p>
								</div>
								<div id="ContainerDetalheDoPedido">
								 	<p class="txt_DadosDoPedido"><?
								 	if($recibo->getFpagamento())
								 	{
								 	    print $recibo->getFpagamento()->getTitulo();
								 	}
								 	else
								 	{
								 		print "Não está definido";
								 	}
								 	?></p>
								</div>
								<div id="ContainerDetalheDoPedido">
								    <p class="txt_ValorDadosDoPedido"><?=$filter->format($recibo->getValor())?></p>
								</div>
							</li>
						</ul>

						<!---->

						<ul id="Status">
							 <li class="tt_Status">Status de pagamento</li>
						</ul>

						<ul>
							<li class="BoxStatus">
							<?php 
							    if(!$recibo->getSpagamento())
							    {
							?>
								<div id="ContainerDetalheDoPedido" class="statusNpedido" rel="<?=$recibo->getIdcontrolerecibo()?>">
								    <a target="_blank" href="https://pagseguro.uol.com.br/v2/checkout/payment.html?code=<?=$recibo->getNpedido()?>" title="Pague Agora"><img class="Txt_PagueAgora" src="<?=$this->basepath()?>/images/PagueAgora.png"></a>
								</div>
								<?php 
							    }else {
                                ?>
                                    <div id="ContainerDetalheDoPedido" class="statusNpedido" rel="<?=$recibo->getIdcontrolerecibo()?>">
    								    <p class="Txt_StatusPagamento"><?=$recibo->getSpagamento()->getTitulo()?></p>
    								</div>
                                <?							    	
							    }
								?>
							</li>
						</ul>

						<!---->

						<ul id="Status">
							 <li class="tt_Status">Status de Envio</li>
						</ul>

						<ul>
							<li class="BoxStatus">
								<div id="ContainerDetalheDoPedido">
								    <p class="Txt_StatusEnvio">
								        <?if(!$recibo->getStatus()) print "Não disponível"; else print $recibo->getStatus();?>
								    </p>
								</div>
							</li>
						</ul>
				
<?php 
					    }
				 }  
				 	    
?>
				</div>

				<!--FIM DO PEDIDOS-->
	
    		</div>
			  	
	</div>
