<form class="formWallpaper">
	<input type="text" class="titulo" placeholder="Digite o Título do Clipping"/><br/>
	<input type="file" class="arquivo" /><br/><br/>
	<input type="submit" value="Adicionar" class="actionAdicionaWallpaper style-adicionar" title="Adicionar Clipping"> <input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Clipping"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>

<div class="accordion" id="accordion2">

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Gerenciar Clipping
      </a>
    </div>

    <div id="collapseOne" class="accordion-body collapse in">

      <div class="accordion-inner">
        <ul class="accordion-wallpaper">
        <?php 
		foreach($this->wallpaper->getFotos() AS $wallpaper)
		{
	?>
         <li>
            <img src="<?=$this->basePath("img/wallpapers/".$wallpaper->getSrc())?>">
            <p><?=$wallpaper->getTituloImagem()?></p>
            <button type="button" class="btn btn-danger deletarAction" title="excluir item" rev="wallpaper" rel="<?=$wallpaper->getIdbaseImagens()?>">Excluir</button>
         </li>
         <?php 
		}
		?>
        </ul>
      </div>
    </div>
  </div>
</div>