<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('NEW Bouts')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
      
       					 ->prependStylesheet($this->basePath() . '/css/reset.css')
        
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        //->prependStylesheet($this->basePath() . '/css/style.css')
        				->prependStylesheet($this->basePath() . '/css/admin.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
       <link rel="stylesheet" href="<?=$this->basePath()?>/css/mobile.css" media="(max-width:1300px)">

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
		<script>
		$(document).ready(function(){
			$(".nav-button").click(function () {
			$(".nav-button,.box-menu").toggleClass("open");
			});    
		});
		</script>

    </head>
    <body>
	   <div class="container"> 
		    <h1>Administrador Bout's</h1>
		    <h5>Nesta sessão você administra completamente o site Bouts.</h5>
	   		<?=$this->content?>
	  	</div>
    </body>
</html>