<form class="formComprar">
	<input type="text" class="titulo" placeholder="Digite o Título do Site"/><br/>
	<input type="text" class="url" placeholder="http://www.centauros.com.br"/><br/>
	<input type="submit" value="Adicionar" class="actionAdicionaBanner style-adicionar" title="Adicionar onde Comprar"> <input type="submit" value="Gerenciar" class="style-gerenciar" title="Adicionar onde Comprar"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>

<br/><br/><br/><br/>




<div class="accordion" id="accordion2">

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Gerenciar Onde Comprar
      </a>
    </div>

    <div id="collapseOne" class="accordion-body collapse in">

      <div class="accordion-inner">
        <ul class="accordion-comprar">
        <li><span>Pratique Bout's</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
        <li><span>Pratique Bout's</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
        <li><span>Pratique Bout's</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
        <li><span>Pratique Bout's</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
      </div>
    </div>
  </div>
</div>