<form class="formProduto">

	<input type="text" class="titulo" placeholder="Titulo do Produto"/> <br/>
	<select  class="form-control tecnologia" style="width:300px;" <?if(!$this->tecnologia) print 'disabled="disabled"'?>>
         <option value="">Selecione tecnologia de amortecimento</option>
         <?php 
         	foreach($this->tecnologia->getSubmenus() AS $tecnologia)
         	{
         		?>
         		<option value="<?=$tecnologia->getIdbaseSubmenu()?>"><?=$tecnologia->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>
	<select  class="form-control categoria" <?if(!$this->categorias) print 'disabled="disabled"'?>>
         <option value="">Selecione uma Categoria</option>
         <?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
         		<option value="<?=$categoria->getIdcategoria()?>"><?=$categoria->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>
	<select  class="form-control subcategoria" disabled="disabled">
         <option value="">Selecione uma Subcategoria</option>
	</select><br/>
	<select  class="form-control modelo" <?if(!$this->modelos) print 'disabled="disabled"'?>>
         <option value="">Selecione o modelo do tenis</option>
         <?php 
         	foreach($this->modelos AS $modelo)
         	{
         		?>
         		<option value="<?=$modelo->getIdmodelo()?>"><?=$modelo->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>
	<input type="file" class="arquivo" /><br/><br/>
	<label class="numeracao" for="" style="cursor:default; color:#222; font-size:14px;">Numeração do Tênis</label>
	<input type="text" class="style-tamanho tamanhoMin" placeholder="Minímo"/> 
    <input type="text" class="style-tamanho tamanhoMax" placeholder="Máximo"/>
    <br/>
	<input type="submit" value="Adicionar" class="actionAdicionaProduto style-adicionar" title="Adicionar Banner"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Banner"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>