<form class="formProduto">

   <!--<div class="alert alert-info">
     <strong>Importante seguir corretamente todos os passos para cadastrar um novo modelo de tênis!</strong>
   </div>
   <div class="alert alert-info">
     O nome do tênis deve ser escrito desta forma, ex: Live ou Spine Teen ou Air Flow Teen. Sempre com a primeira letra em maiúscolo.<br/><br/> 
     O sistema gera automaticamente o texto TÊNIS BOUT'S.
   </div>
   <div class="alert alert-info">
     Descreva um pequeno texto sobre as informações do tênis.
   </div>
   <div class="alert alert-info">
     Digite o modelo do tenis ex: 9036-701. Caso conter letras colocar sempre em letra maiúsculas.
   </div>
   <div class="alert alert-info">
     A resolução ideal para as imagens dos tenis é 650 x 400 com fundo transparente na extenção png, sempre com o tênis centralizado.  
   </div>-->

	<input type="text" class="titulo" placeholder="Nome do Tênis"/> <br/>
   <textarea name="mensagem" class="statusDescricaoTenis" placeholder="Uma breve descrição do tênis"></textarea><br/>
	<input type="text" class="modelo" placeholder="Digite o modelo do tênis"/> <br/>
	<select  class="form-control tecnologia" style="width:300px;" <?if(!$this->tecnologia) print 'disabled="disabled"'?>>
         <option value="">Selecione Tecnologia de Amortecimento</option>
         <?php 
         	foreach($this->tecnologia->getSubmenus() AS $tecnologia)
         	{
         		?>
         		<option value="<?=$tecnologia->getIdbaseSubmenu()?>"><?=$tecnologia->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>
	<select  class="form-control categoria" <?if(!$this->categorias) print 'disabled="disabled"'?>>
         <option value="">Selecione uma Categoria</option>
         <?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
         		<option value="<?=$categoria->getIdcategoria()?>"><?=$categoria->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>
	<select  class="form-control subcategoria" disabled="disabled">
         <option value="">Selecione uma Subcategoria</option>
	</select><br/>
	<input type="file" class="arquivo" /><br/><br/>
	<label class="numeracao" for="" style="cursor:default; color:#222; font-size:14px;">Numeração do Tênis</label>
	<input type="text" class="style-tamanho tamanhoMin" placeholder="Minímo"/> 
    <input type="text" class="style-tamanho tamanhoMax" placeholder="Máximo"/>
    <br/>
	<input type="submit" value="Adicionar" class="actionAdicionaProduto style-adicionar" title="Adicionar Banner"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Banner"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>


<br/><br/><br/><br/>




<div class="accordion" id="accordion2">

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Aventura
      </a>
    </div>

    <div id="collapseOne" class="accordion-body collapse in">

      <div class="accordion-inner">
        <ul>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
        Running
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
        Masculino
      </a>
    </div>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">
        <ul>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/viewport-imagem.png")?>">
            <p><strong>Tênis:</strong> Air Flow Teen</p>
            <p><strong>Modelo:</strong> 8974-785</p>
            <button type="button" title="excluir item">Excluir</button>
         </li>
        </ul>
      </div>
    </div>
  </div>


</div>