<form class="formTecnologia">

	<input type="text" class="titulo" placeholder="Titulo da Tecnologia"/> <br/>
	<textarea name="mensagem" class="statusMensagem" placeholder="Descrição da Tecnologia"></textarea><br/>

    <label style="cursor:default; color:#222; font-size:14px;">Imagem do Logo:</label><input type="file" class="arquivo"/><br/><br/>
	<label style="cursor:default; color:#222; font-size:14px;">Imagem de Destaque:</label><input type="file" class="arquivo"/><br/><br/>

	<input type="submit" value="Adicionar" class="actionAdicionaProduto style-adicionar" title="Adicionar Banner"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Banner"><br/>
</form>

<div class="accordion" id="accordion2">

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Gerenciar Tecnologia
      </a>
    </div>

    <div id="collapseOne" class="accordion-body collapse in">

      <div class="accordion-inner">
        <ul class="accordion-tec">
		 <li><span>Fly TS</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
		 <li><span>Fly TS</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
		 <li><span>Fly TS</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
		 <li><span>Fly TS</span><button type="button" class="btn btn-danger" title="excluir item">Excluir</button></li>
	    </ul>
      </div>
    </div>
  </div>
</div>