<form class="formTecnologia">

	<input type="text" class="titulo" placeholder="Titulo da Tecnologia"/> <br/>
	<textarea name="mensagem" class="statusMensagem" placeholder="Descrição da Tecnologia"></textarea><br/>

    <label style="cursor:default; color:#222; font-size:14px;">Imagem do Logo:</label><input type="file" class="arquivo"/><br/><br/>
	<label style="cursor:default; color:#222; font-size:14px;">Imagem de Destaque:</label><input type="file" class="arquivo"/><br/><br/>

	<input type="submit" value="Adicionar" class="actionAdicionaProduto style-adicionar" title="Adicionar Banner"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Banner"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>