<form class="formWallpaper">
	<input type="text" class="titulo" placeholder="Digite o Título do Wallpaper"/><br/>
	<input type="file" class="arquivo" /><br/><br/>
	<input type="submit" value="Adicionar" class="actionAdicionaBanner style-adicionar" title="Adicionar Wallpaper"> <input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Wallpaper"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>