<form class="formWallpaper">
	<input type="text" class="titulo" placeholder="Digite o Título do Wallpaper"/><br/>
	<input type="file" class="arquivo" /><br/><br/>
	<input type="submit" value="Adicionar" class="actionAdicionaBanner style-adicionar" title="Adicionar Wallpaper"> <input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Wallpaper"><br/>
	<div style="padding:5px;display:none">
	<h4>Banners ativos:</h4>
		 <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="200"></a>
	</div>
</form>

<br/><br/><br/><br/>




<div class="accordion" id="accordion2">

  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Gerenciar Wallpaper
      </a>
    </div>

    <div id="collapseOne" class="accordion-body collapse in">

      <div class="accordion-inner">
        <ul class="accordion-wallpaper">
         <li>
            <img src="<?=$this->basepath("img/wallpapers/teste.jpg")?>">
            <p><strong>Título:</strong> Air Flow Teen</p>
            <button type="button" class="btn btn-danger" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/wallpapers/teste.jpg")?>">
            <p><strong>Título:</strong> Air Flow Teen</p>
            <button type="button" class="btn btn-danger" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/wallpapers/teste.jpg")?>">
            <p><strong>Título:</strong> Air Flow Teen</p>
            <button type="button" class="btn btn-danger" title="excluir item">Excluir</button>
         </li>
         <li>
            <img src="<?=$this->basepath("img/wallpapers/teste.jpg")?>">
            <p><strong>Título:</strong> Air Flow Teen</p>
            <button type="button" class="btn btn-danger" title="excluir item">Excluir</button>
         </li>
        </ul>
      </div>
    </div>
  </div>
</div>