<form class="formTecnologia">
	<input type="text" class="titulo" placeholder="Titulo da Tecnologia"/><br/>
	<textarea name="mensagem" class="statusMensagem" placeholder="Descrição da Tecnologia"></textarea><br/>

  <label style="cursor:default; color:#222; font-size:14px;">Imagem do Logo:</label><input type="file" class="arquivo"/><br/><br/>
	<label style="cursor:default; color:#222; font-size:14px;">Imagem de Destaque:</label><input type="file" class="arquivo"/><br/><br/>

	<input type="submit" value="Adicionar" class="actionAdicionaTecnologia style-adicionar" title="Adicionar Tecnologia"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Tecnologia"><br/>

  <span>
    <div class="alert alert-block">Atenção! Esse espaço serve para subir as perspectivas das tecnologias:</div>
     <label style="cursor:default; color:#222; font-size:14px;">Primeira Perspectiva:</label><input type="file" class="arquivo"/><br/><br/>
     <label style="cursor:default; color:#222; font-size:14px;">Segunda Perspectiva:</label><input type="file" class="arquivo"/><br/><br/>
     <label style="cursor:default; color:#222; font-size:14px;">Terceira Perspectiva:</label><input type="file" class="arquivo"/><br/><br/>
     <label style="cursor:default; color:#222; font-size:14px;">Quarta Perspectiva:</label><input type="file" class="arquivo"/><br/><br/>
  </span>
</form>

<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Gerenciar Tecnologia
      </a>
    </div>

    <div id="collapseOne" class="accordion-body collapse in">

      <div class="accordion-inner">
        <ul class="accordion-tec">
         <?php 
        	foreach($this->tecnologia AS $tec)
        	{
        ?>
    		 <li><span><?=$tec->getSubmenu()->getNome()?></span>
          <button type="button" class="btn btn-info" title="editar item" rev="tecnologiaAdm" rel="<?=$tec->getSubmenu()->getIdbaseSubmenu()?>">Editar</button>
          <button type="button" class="btn btn-danger deletarAction" title="excluir item" rev="tecnologiaAdm" rel="<?=$tec->getSubmenu()->getIdbaseSubmenu()?>">Excluir</button>

          <section id="editar-tec">

            <label style="cursor:default; color:#222; font-size:14px;">Título:</label>
            <input type="text" class="titulo" placeholder="Titulo da Tecnologia"/>
            <a class="ed-tc" href="" title="editar sub-categoria" style="top:-5px">alterar</a>
            <br/>

            <label style="cursor:default; color:#222; font-size:14px;">Descrição:</label>
            <textarea name="mensagem" class="statusMensagem" placeholder="Descrição da Tecnologia"></textarea><br/>
            <a class="ed-tc" href="" title="editar sub-categoria">alterar</a>
            
           <ul>
             <li class="list-tec">
              <img src="<?=$this->basePath()?>/img/tecnologia/load_535acbb648cac.png">
              <input type="file" class="arquivo"/>
             </li>

             <li class="list-tec">
              <img src="<?=$this->basePath()?>/img/tecnologia/load_535acbb648fc3.png">
              <input type="file" class="arquivo"/>
            </li>

             <li class="list-tec">
              <img src="<?=$this->basePath()?>/img/tecnologia/load_535acbb6488e9.png">
              <input type="file" class="arquivo"/>
            </li>

             <li class="list-tec">
              <img src="<?=$this->basePath()?>/img/tecnologia/load_535acbb64962b.png">
              <input type="file" class="arquivo"/>
            </li>

             <li class="list-tec">
              <img src="<?=$this->basePath()?>/img/tecnologia/load_535acbb649315.png">
              <input type="file" class="arquivo"/>
            </li>

             <li class="list-tec">
              <img src="<?=$this->basePath()?>/img/tecnologia/load_535acbb6485a5.png">
              <input type="file" class="arquivo"/>
            </li>

           </ul>   
          </section>

        </li>
	   	<?php 
        	}
	   	?>
	   	 </ul>
      </div>
    </div>
  </div>
</div>
