<li class="sub-menu box-lista">

					<a class="produtos" href="#">
						produtos
					</a>

					<ul>
						<li>
							<a href="#">
								<h6>Homem</h6>
								<p>Calçados masculinos</p>
							</a>
						</li>

						<li>
							<a href="#">
								<h6>Mulher</h6>
								<p>Calçados femininos</p>
							</a>
						</li>

						<li>
							<a href="#">
								<h6>Bout's Teen</h6>
								<p>Masculino</p>
								<p>Feminino</p>
							</a>
						</li>

					</ul>
				</li>