<header class="h-container-top box-paralax">
    <section class="h-produtos">
        <h2><?=$this->dadosMatchedRouter['tituloCampanha']?></h2>

        <div>

            <ul>
                <li><a class="dt-voltar" href="javascript: history.go(-1)" title="Voltar">Voltar &nbsp;|</a></li>
                <li><a href="<?=$this->url("home")?>" title="Página Inicial">Página Inicial &nbsp;-</a></li>
                <?php
                if($this->dadosMatchedRouter['matchedRouteCaminho'] != false)
                {
                if(!isset($this->dadosMatchedRouter['matchedRouteCaminho']['lista'])) 
                {
                	if(is_array($this->dadosMatchedRouter['matchedRouteCaminho']['rota']))
                	{
                ?>
                <li><a href="<?=$this->url($this->dadosMatchedRouter['matchedRouteCaminho']['rota']['MatchedRouteName'],$this->dadosMatchedRouter['matchedRouteCaminho']['rota'][0])?>" title="Produtos"><?=$this->dadosMatchedRouter['matchedRouteCaminho']['nome']?></a></li>
                <?php
                	} 
                	else {
                	?>
                <li><a href="<?=$this->url($this->dadosMatchedRouter['matchedRouteCaminho']['rota'])?>" title="Produtos"><?=$this->dadosMatchedRouter['matchedRouteCaminho']['nome']?></a></li>
               		 <?php	
                	}
                }
                else 
                {
                	foreach($this->dadosMatchedRouter['matchedRouteCaminho']['lista'] as $lista)
                	{
                	?>
                	 <li><a href="<?=$this->url($lista['rota']['MatchedRoute'],$lista['rota']['arrayDefines'])?>" title="Produtos"><?=ucwords($lista['nome'])?>&nbsp;&nbsp;-</a></li>
                	<?php
                	}
                }
                
                }
                ?>
            </ul>

            <br/>

            <ul class="box-produto">
             <?php
             if($this->dadosMatchedRouter['matchedRouteCaminho'] != false)
             {
                if(!isset($this->dadosMatchedRouter['matchedRouteCaminho']['lista'])) 
                {
                	if(is_array($this->dadosMatchedRouter['matchedRouteCaminho']['rota']))
                	{
                ?>
               			<li><a class="tt-produto" href="<?=$this->url($this->dadosMatchedRouter['matchedRouteCaminho']['rota']['MatchedRouteName'],$this->dadosMatchedRouter['matchedRouteCaminho']['rota'][0])?>" title="Calçados femininos"><?=$this->dadosMatchedRouter['matchedRouteCaminho']['subtitulo']?></a></li>
                <?php 
                	}
                	else
                	{
                		?>
                		<li><a class="tt-produto" href="<?=$this->url($this->dadosMatchedRouter['matchedRouteCaminho']['rota'])?>" title="Calçados femininos"><?=$this->dadosMatchedRouter['matchedRouteCaminho']['subtitulo']?></a></li>
                		 <?php 
                	}
                }
                else
                {
                	?>
                	<li><a class="tt-produto" href="" title="Calçados femininos"><?=$this->dadosMatchedRouter['matchedRouteCaminho']['subtitulo']?></a></li>
                	<?php
                }
             }  
                ?>
            </ul>

        </div>

    </section>
</header>