<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
      
       					 ->prependStylesheet($this->basePath() . '/css/reset.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/galery/engine1/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
       <!--<link rel="stylesheet" href="<?=$this->basePath()?>/css/mobile.css" media="(max-width:1300px)">-->
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/site.js')
                                      ->prependFile($this->basePath() . '/js/jquery.elevateZoom-3.0.8.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
                                      ->prependFile($this->basePath() . '/js/html5shiv.js')                                   
                                      ->prependFile($this->basePath() . '/js/jquery-1.10.2.js') ?>
                                      <script type="text/javascript">
	var basePatch  = '<?=$this->basePath()?>';
		</script>
    </head>
    <body>
    <div class="loadAjax">

    </div>
    <?php 
    /*
    print $this->partial('menu/menu.phtml', array('menu' => $this->menu, 'menuListaTenis' => $this->menuListaTenis));
    print $this->content; 
    */
    ?>

    <section class="menu">

	 	<nav>

	 		<h1><a href="<?=$this->url("home")?>" title="Página Inicial"><img alt="Página Inicial" src="<?=$this->basePath()?>/img/logo-bouts.png"></a></h1>

	 		<?php 
	 		print $this->partial('menu/menu.phtml', array('menu' => $this->menu, 'menuListaTenis' => $this->menuListaTenis));
	 		?>

	 		<div class="usuario">

 				<figure class="wall">
 					<a href="<?=$this->url("wallpaper")?>" title="Clipping">Clipping</a>
 				</figure>

 				<figure class="contato">
 					<a href="" class="abrirContato" title="fale conosco">fale&nbsp;conosco</a>
 				</figure>

 			</div>

	 	</nav>

 	</section>
<?php 
	if($this->matchedRoute != "home" && !isset($this->desableMenu))
	{
		print $this->partial('layout/caminho.phtml',array("dadosMatchedRouter" => $this->matchedTitlesRouter));
	}
    else{
        ?>

        <header class="h-container-top">

        <section class="h-news">
            
            <div class="newsletter">

                <h5>Newsletter Bout’s</h5>

                <p>Cadastre-se para receber notícias,<br/>
                   lançamento e ofertas.</p>

                <input class="news-top" type="text" name="email" placeholder="Escreva seu endereço de e-mail"/>

                <button class="vd" type="submit" name="enviar" title="Cadastrar">Cadastrar</button>

            </div>

        </section>
     </header>

        <?php
    }
?>

 	<!--  ***************************************************************************  -->

 	<section class="container">
			<?=$this->content; ?>
	</section>

	<footer>

		<section class="h-container-bottom">

	 		<section class="h-news">

	 			<div class="newsletter newsletter-bottom">
				
		         <h5>Newsletter Bout’s</h5>

				  <p>Cadastre-se para receber notícias,<br/>
					lançamento e ofertas.</p>

				  <input class="news-bottom" type="text" name="email" placeholder="Escreva seu endereço de e-mail"/>

		          <button class="az" type="submit" name="enviar" title="Cadastrar">Cadastrar</button>

	            </div>

	 		</section>

 	    </section>

 	    <section class="menu-bottom">
			 <?php 
		    	foreach($this->menu AS $menu)
		    	{
		    		if($menu->getTipo()->getNome() == "parceiros")
		    		{
		    			?>
		    			
					 	    	<ul class="mb-comprar">
					 	    		<li>
					 	    			<a class="tt-menu-bottom" href="">Comprar agora</a>
					 	    		</li>
					 	    		<?php 
									 		foreach($menu->getSubmenus() AS $data)
									 		{
									 	?>
					 	    		<li>
					 	    			<a class="txt-menu-bottom" href="<?=$data->getUrl()?>" target="_blank"><?=$data->getNome()?></a>
					 	    		</li>
											<?php 
									 		}
											?>
					 	    	</ul>
		    			<?php
		    		}
		    		else if($menu->getTipo()->getNome() == "tenis")
		    		{
		    			?>
		    			<ul class="mb-produtos">
				 	    		<li>
				 	    			<a class="tt-menu-bottom dt-tt" href="">Produtos</a>
				 	    		</li>
				 	    		<?php 
							foreach($this->menuListaTenis AS $menuTenis)
							{
								if(count($menuTenis->getSubcategorias()) >= 1)
								{
						?>
				 	    		<li>
				 	    			<a class="sub-produto" href="<?=$this->url("produto",array("categoria" => $menuTenis->getSlug()));?>">
				 	    				<strong><?=ucwords($menuTenis->getNome())?></strong></a>
				 	    		</li>
				 	    				<?php 
									foreach($menuTenis->getSubcategorias() AS $subcategoria)
									{
										if(count($subcategoria->getProdutos()) >= 1)
										{
								?>
				 	    		<li>
				 	    			<a class="txt-menu-bottom txt-produto" href="<?=$this->url("produto/produto-subcategoria",array("categoria" => $menuTenis->getSlug(), "subcategoria" => $subcategoria->getSlug()));?>"><?=$subcategoria->getNome()?></a>
				 	    		</li>
				 	    		<?php 
										}
									}	
								}
							}	
				 	    		?>
				 	    </ul>
		    			<?php
		    		}
		    		else if($menu->getTipo()->getNome() == "tecnologia")
		    		{
		    			?>
		    			<ul class="mb-tecnoligia">
				 	    		<li>
				 	    			<a class="tt-menu-bottom" href="">Tecnologia</a>
				 	    		</li>
				 	    		<?php 
		foreach($menu->getSubmenus() AS $sub)
		{
	?>
				 	    		<li>
				 	    			<a class="txt-menu-bottom" href="<?=$this->url("tecnologia/tecnologia-detalhe",array("slug" => $sub->getSlug()))?>"><?=$sub->getNome()?></a>
				 	    		</li>
				 	    		<?php
				 	    		}
		?>
				 	    	</ul>
		    			<?php
		    		}
		    	}
		    ?>
		    
 	    	<ul class="info">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Outras informações</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="<?=$this->url("midia")?>">Mídia</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom abrirContato" href="">Fale conosco</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="<?=$this->url("wallpaper")?>">Clipping</a>
 	    		</li>
 	    	</ul>

 	    	<ul class="mb-redes">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Bout’s nas redes sociais</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="https://pt-br.facebook.com/tenisbouts" target="_blank" title="Facebook">Facebook</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="https://twitter.com/boutsoficial" target="_blank" title="Twitter">Twitter</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="http://www.youtube.com/user/boutstiptoe?feature=mhee" target="_blank" title="You Tube">You Tube</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="http://instagram.com/tenisbouts" target="_blank" title="Instagram">Instagram</a>
 	    		</li>
 	    	</ul>
 	    </section>

 	    <section class="h-container-footer">
 	    	<div class="copyright">
 	    		<figure class="bouts-copyright">
 	    			<img alt="Logo Tênis Bout´s" title="Bout's sua vida em movimento" src="<?=$this->basePath()?>/img/logo-bouts-footer.png">
 	    			<figcaption>Copyright © BOUT'S 2014  -  SUA VIDA EM MOVIMENTO</figcaption>
 	    		</figure>
 	    	</div>
        </section>

        <section class="bee-happy">
        	<p>Visite também o site da <a href="http://www.beehappy.com.br/" target="_blank" title="Bee-Happy">Bee-Happy</a></p>
        </section>

	</footer>


	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  ga('create', 'UA-54401250-1', 'auto');
	  ga('send', 'pageview');
    </script>
    
    </body>
</html>