<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('NEW Bouts')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
      
       					 ->prependStylesheet($this->basePath() . '/css/reset.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/galery/engine1/style.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
       <link rel="stylesheet" href="<?=$this->basePath()?>/css/mobile.css" media="(max-width:1300px)">
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/site.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js') 
                                      ->prependFile($this->basePath() . '/js/html5shiv.js')                                   
                                      ->prependFile($this->basePath() . '/js/jquery-1.10.2.js') ?>


    </head>
    <body>
    <?php 
    /*
    print $this->partial('menu/menu.phtml', array('menu' => $this->menu, 'menuListaTenis' => $this->menuListaTenis));
    print $this->content; 
    */
    ?>
    <header class="h-container-top">

 		<section  class="h-topo">

 			<div class="redes-sociais">

				<div id="fb-root"></div>
				<script>(function(d, s, id) {
				  var js, fjs = d.getElementsByTagName(s)[0];
				  if (d.getElementById(id)) return;
				  js = d.createElement(s); js.id = id;
				  js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1";
				  fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>
				<div class="fb-like" data-href="https://www.facebook.com/tenisbouts?fref=ts" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>

				<div class="twitter">
					<a href="https://twitter.com/share" class="twitter-share-button" data-url="https://twitter.com/BoutsOficial" data-via="BoutsOficial" data-related="BoutsOficial">Tweet</a>
	                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                </div>

 			</div>

 			<div class="usuario">

 				<figure class="wall">
 					<a href="">
 					<figcaption>Wallpaper</figcaption>
 				    </a>
 				</figure>

 				<figure class="contato" >
 					<a href="">
 					<figcaption>fale conosco</figcaption>
 				    </a>
 				</figure>

 			</div>


 		</section>

 	</header>

 	<section class="menu">

	 	<nav>
	 		<h1><a href="" title="Home" alt="Bout's"><img src="img/logo-bouts.png"></a></h1>

	 		 <button class="nav-button">Menu</button>

	 		<?php 
	 		print $this->partial('menu/menu.phtml', array('menu' => $this->menu, 'menuListaTenis' => $this->menuListaTenis));
	 		?>

	 	</nav>

 	</section>

 	<section class="container">
			<?=$this->content; ?>
	</section>

	<!--<footer>

		<header class="h-container-bottom">

	 		<section class="h-news">

	 			<div class="newsletter newsletter-bottom">

		 			<h5>Newsletter Bout’s</h5>

		 			<p>Cadastre-se para receber notícias,<br/>
		            lançamento e ofertas.</p>

		            <input type="text" name="email" placeholder="Escreva seu endereço de e-mail"/>

		            <button class="az" type="submit" name="enviar" title="Cadastrar">Cadastrar</button>

	            </div>

	 		</section>

 	    </header>

 	    <section class="menu-bottom">

 	    	<ul class="mb-comprar">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Comprar agora</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Centauro</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Passarela</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Humanitarian</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Lojas Silva</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Azul Calçados</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Kallan</a>
 	    		</li>

 	    	</ul>

 	    	<ul class="mb-produtos">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Produtos</a>
 	    		</li>
 	    		<li>
 	    			<a href=""><strong>Homem</strong></a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Calçados masculinos</a>
 	    		</li>
 	    		<li>
 	    			<a href="" ><strong>Mulher</strong></a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Calçados femininos</a>
 	    		</li>
 	    		<li>
 	    			<a href=""><strong>Bout’s Teen</strong></a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Masculino</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Feminino</a>
 	    		</li>
 	    	</ul>

 	    	<ul class="mb-tecnoligia">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Tecnologia</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Fly TS</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Gel TS</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Spirtal TS</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Tower TS</a>
 	    		</li>
 	    	</ul>

 	    	<ul class="info">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Outras informações</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Mídia</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Fale conosco</a>
 	    		</li>
 	    		<li>
 	    			<a class="txt-menu-bottom" href="">Wallpapers</a>
 	    		</li>
 	    	</ul>

 	    	<ul class="mb-redes">
 	    		<li>
 	    			<a class="tt-menu-bottom" href="">Bout’s nas redes sociais</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="https://pt-br.facebook.com/tenisbouts" target="_blank">Facebook</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="https://twitter.com/boutsoficial" target="_blank">Twitter</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="http://www.youtube.com/user/boutstiptoe?feature=mhee" target="_blank">You Tube</a>
 	    		</li>
 	    		<li>
 	    			<a class="box-mb-redes" href="http://instagram.com/tenisbouts" target="_blank">Instagram</a>
 	    		</li>
 	    		
 	    	</ul>
 	    </section>

 	    <header class="h-container-top">

 	    	<div class="copyright">
 	    		<figure class="bouts-copyright">
 	    			<img src="img/logo-bouts-footer.png">
 	    			<figcaption>Copyright © BOUT'S 2014  -  SUA VIDA EM MOVIMENTO</figcaption>
 	    		</figure>

 	    		<figure class="spicy">
 	    			<figcaption>Desenvolvido por</figcaption>
 	    			<a href="" target="_blank" title="Spicy.comm" alt="Spicy.comm"><img src="img/logo-spicy.png"></a>
 	    		</figure>

 	    		<span><a class="vt-topo" title="Voltar topo" alt="Voltar topo" href="">Voltar topo</a></span>

 	    	</div>
        </header>

        <section class="bee-happy">
        	<p>Visite também o site da <a href="" target="_blank" title="Bee-Happy">Bee-Happy</a></p>
        </section>

	</footer>-->
    
    </body>
</html>