<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>BlueScalee free Magento Template from WebAndPeople</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Premium Magento Template - Magento eCommerce platform." />
<meta name="keywords" content="magento, ecommerce, theme, template" />
<meta name="robots" content="INDEX,FOLLOW" />
<meta name="Designer" content="WebAndPeople Magento design - http://webandpeople.com" />
<link rel="icon" href="http://web-experiment.info/magento14/skin/frontend/default/bluescale/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="http://web-experiment.info/magento14/skin/frontend/default/bluescale/favicon.ico" type="image/x-icon" />



<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = 'http://web-experiment.info/magento14/js/blank.html';
    var BLANK_IMG = 'http://web-experiment.info/magento14/js/spacer.gif';
	var SKIN_URL = 'http://web-experiment.info/magento14/skin/frontend/default/bluescale/';
	var basePatch  = '<?=$this->basePath()?>';
	
//]]>
	
</script>


<link rel="stylesheet" type="text/css" href="http://web-experiment.info/magento14/media/css/099f67297efb3df1420e41e567acc4e5.css" media="all" />
<link rel="stylesheet" type="text/css" href="http://web-experiment.info/magento14/media/css/2912a3f52ec3c830de1b697a6e803ab0.css" media="print" />
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/styleNovoLayout.css')
                        ?>
<?php echo $this->headScript()->prependFile($this->basePath() . '/js/usuario.js')
                                      ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
   
   
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="http://web-experiment.info/magento14/media/css/1064e11bec2ec9abcb3e449694260346.css" media="all" />
<![endif]-->
<!--[if lt IE 7]>
<script type="text/javascript" src="http://web-experiment.info/magento14/js/lib/ds-sleight.js"></script>
<script type="text/javascript" src="http://web-experiment.info/magento14/skin/frontend/base/default/js/ie6.js"></script>
<![endif]-->

<script type="text/javascript">
//<![CDATA[
optionalZipCountries = [];
//]]>
</script>
<script type="text/javascript">var Translator = new Translate([]);</script><script src="/js/webandpeople/SpryMenuBar.js" type="text/javascript"></script>
<link href="/js/webandpeople/SpryMenuBarVertical.css" rel="stylesheet" type="text/css" />
<script type="text/javascript">    var _gaq = _gaq || [];   _gaq.push(['_setAccount', 'UA-6063824-5']);   _gaq.push(['_trackPageview']);    (function() {     var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;     ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';     var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);   })();  </script></head>
<body class=" cms-index-index cms-home">

       <!--ERRO-->
        <div id="form_erro" style="display:none">
          <div id="BoxFormErro">
                <div class="modelNotificacao">
                   <p class="atencaoErro"><!-- Titulo Box --></p>
                   <p class="erro"><!-- Lista de mensagens --></p>
                   <span class="tipo_erro"></span>
                   <br/>
                   <a href="" class="tentarNovamente"><!-- Titulo Botão --></a>
                </div> 
          </div>
        </div>
<div class="wrapper">
        <noscript>
        <div class="noscript">
            <div class="noscript-inner">
                <p><strong>We detected that your JavaScript seem to be disabled.</strong></p>
                <p>You must have JavaScript enabled in your browser to utilize the functionality of this website.</p>
            </div>
        </div>
    </noscript>
    <div class="page">
        <div class="header-container">
    <div class="header">
                <h2 class="logo"><strong>Premium Magento Template</strong><a href="<?=$this->url("home")?>" title="Premium Magento Template" class="logo"><img src="http://web-experiment.info/magento14/skin/frontend/default/bluescale/images/logo.gif" alt="Premium Magento Template" /></a></h2>
                <div class="head_phone_block">
<p class="phone"><small>Contato: (+11)</small> 253-243-2001</p>
</div>        <div class="quick-access">
            <p class="welcome-msg"></p>
            <div class="block-cart-top">
        <div class="block-content">
        <?
						if($this->carrinhoLista['listaAtual'])
						{
					?>
                  <div class="actions">
        <a class="finalizarPagamento" href="<?=$this->url("publico-finaliza-compra")?>"><button type="button" title="Checkout" class="button-small"><span><span>Finalizar</span></span></button></a>
    </div>
        <div class="summary">
                        <p class="amount"><span class="quantItens"><?=count($this->carrinhoLista['listaAtual'])?></span> items: <span class="price"><?=$this->carrinhoLista['valorTotal']?></span></p>
                    </div>
						<?
						}
						else
						{
						?>
						<div class="actions">
        <a style="display:none" class="finalizarPagamento" href="<?=$this->url("publico-finaliza-compra")?>"><button type="button" title="Checkout" class="button-small"><span><span>Finalizar</span></span></button></a>
    					</div>
        <div class="summary">
                        <p class="amount"><span class="quantItens">0</span> items: <span class="price">$0.00</span></p>
                    </div>	
						<?
						}
						?>
    
    </div>
</div>
            <ul class="links">
            <li class="first" ><a href="<?=$this->url("publico-carrinho-compra")?>" title="My Wishlist" class="top-link-wishlist">Meu Carrinho</a></li>
            <li ><a href="<?php print $this->url("Usuario/UsuarioAction",array("controller"=>"Login","action" => "logout"))?>" title="Log In" style="color:green">Sair</a></li>
            <li class=" last" ><a href="<?=$this->url("Painel-usuario")?>" title="My Account" >Acompanhe seus pedidos</a></li>
    </ul>
            
        </div>
            </div>
</div>
                        <div class="nav-container">
    <ul id="nav">
    	 <li><a class="home" href="<?=$this->url("home")?>"><span>Inicio</span></a></li>
    	 <?php
                        $a = 1;
                        foreach($this->categorias as $categoria): 
						?> 
    				 <li onmouseover="toggleMenu(this,1)" onmouseout="toggleMenu(this,0)" class="level0 nav-3 parent">
					<a href="#"><span><?php echo $categoria->getNome(); ?></span></a>
					<ul class="level0">
					<?php
					                                    $i = 1; 
					                                    foreach($categoria->getSubcategorias() as $subcategoria): 
					                                        if(count($subcategoria->getProdutos()) > 0): 
					                                    ?>
					<li class="level1 nav-3-1">
					<a href="<?php echo $this->url('publico-categoria/publico-categoria-e-subcategoria', array('categoriaslug'=>$categoria->getSlug(), 'subcategoriaslugSub'=>$subcategoria->getSlugSubcategoria())); ?>"><span>Fragrances</span></a>
					</li>
					<?php $i--; endif; endforeach; ?> 
					</ul></li>
					<?php $a--; endforeach; ?>
    </ul>
</div>
<div class="search-block">
    <p><span><strong>Olá <?=$this->infoUser->getLogin()?></strong>, seja bem vindo a nossa loja</span></p>    <form id="search_mini_form" action="http://web-experiment.info/magento14/bluescale/catalogsearch/result/" method="get">
    <div class="form-search">
        <label for="search">Encontre:</label>
        <input id="search" type="text" name="q" value="" class="input-text" />
        <button type="submit" title="Search" class="button"><span><span>Search</span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Search entire store here...');
            searchForm.initAutocomplete('http://web-experiment.info/magento14/bluescale/catalogsearch/ajax/suggest/', 'search_autocomplete');
        //]]>
        </script>
    </div>
</form>
</div>
        <div class="main-container <?if($this->matchedRoute == "publico-carrinho-compra" || $this->matchedRoute == "publico-finaliza-compra") print "col1-layout"; else if($this->matchedRoute != "publico-categoria") print "col2-left-layout"; else print "col3-layout";?>">
        <div class="main">
        
 <?php
 				if($this->matchedRoute != "home")
 				{
                    print  $this->partial("layout/caminho",array("caminhoDefines" => $this->caminhoDefines));
 				}    
                  ?>
                  		<?php 
                  			if($this->matchedRoute != "publico-categoria")
                  			{
                  		?>
                                <div class="col-main">
                                <?php echo $this->content; ?>
                                </div>
                                <?php 
                  			}    
                  			else
                  			{
                  				?>
                  				<div class="col-wrapper">
                  				 <div class="col-main">
                                <?php echo $this->content; ?>
                                </div>
                                <div class="col-left sidebar"><div class="block block-currency">
    <div class="block-title">
        <strong><span>Select Your Currency</span></strong>
    </div>
    <div class="block-content">
        <select name="currency" title="Select Your Currency" onchange="setLocation(this.value)">
                    <option value="http://web-experiment.info/magento14/bluescale/directory/currency/switch/currency/EUR/uenc/aHR0cDovL3dlYi1leHBlcmltZW50LmluZm8vbWFnZW50bzE0L2JsdWVzY2FsZS9hcHBhcmVsL2tpZHMtYmFieS5odG1s/">
                Euro - EUR            </option>
                    <option value="http://web-experiment.info/magento14/bluescale/directory/currency/switch/currency/USD/uenc/aHR0cDovL3dlYi1leHBlcmltZW50LmluZm8vbWFnZW50bzE0L2JsdWVzY2FsZS9hcHBhcmVsL2tpZHMtYmFieS5odG1s/" selected="selected">
                US Dollar - USD            </option>
                </select>
    </div>
</div>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span>Browse By</span></strong>
    </div>
    <div class="block-content">
        <dl id="narrow-by-list2">
            <dt class="last odd">Category</dt>
            <dd class="last odd">
                <ol>
                                                        <li>
                        <a href="http://web-experiment.info/magento14/bluescale/apparel/kids-baby/shirts-tops.html">Shirts &amp; Tops</a> (21)
                    </li>
                                                                            <li>
                        <a href="http://web-experiment.info/magento14/bluescale/apparel/kids-baby/baby-set.html">Baby Set</a> (13)
                    </li>
                                                                            <li>
                        <a href="http://web-experiment.info/magento14/bluescale/apparel/kids-baby/baby-pants.html">Baby Pants</a> (13)
                    </li>
                                                                            <li>
                        <a href="http://web-experiment.info/magento14/bluescale/apparel/kids-baby/baby-dresses.html">Baby Dresses</a> (13)
                    </li>
                                                                            <li>
                        <a href="http://web-experiment.info/magento14/bluescale/apparel/kids-baby/baby-rompers.html">Baby Rompers</a> (31)
                    </li>
                                                    </ol>
            </dd>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list2')</script>
    </div>
</div>
<div><div class="block block-subscribe">
    <div class="block-title">
        <strong><span>Newsletter</span></strong>
    </div>
    <form action="http://web-experiment.info/magento14/bluescale/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <label for="newsletter">Sign up for our newsletter:</label>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email">
            </div>
            <div class="actions">
                <button type="submit" title="Subscribe" class="button"><span><span>Subscribe</span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
</div>
<div class="block">
<div class="block-title"><strong><span>Special Magento Hosting</span></strong></div>
<div class="block-content">
<p style="padding-left: 8px; padding-bottom: 0; margin-bottom: 0;"><strong><a title="Magento Hosting" href="http://magenting.com">Magento Hosting</a><br> with autoinstallation feature</strong> <br> <strong>Fast, Reliable, Secure</strong></p>
</div>
</div>
<div class="block block-download">
<div class="block-title"><strong><span>Download theme free</span></strong></div>
<div class="block-content">
<p><a class="download" title="Download Magento Theme Free" href="http://web-experiment.info/magento/media/downloads/webandpeople-magento-1.4-1.5-1.6.1.0-theme-bluescale-1.2.2.zip"><span>Download theme free</span></a></p>
</div>
</div>
<div>
<ul id="MenuBar5" class="MenuBarVertical buy_theme_left MenuBarActive">
<li><a class="MenuBarItemSubmenu spec_th" title="Specials for this theme" href="javascript:;">Magento theme specials</a> 
<ul class="">
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'gray']);" href="http://web-experiment.info/magento14/bluescale/bg_gray">Gray Background</a></li>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'white']);" href="http://web-experiment.info/magento14/bluescale/bg_white">White Background</a></li>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'flower']);" href="http://web-experiment.info/magento14/bluescale/bg_blue">Flower Background</a></li>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'main']);" href="http://web-experiment.info/magento14/bluescale/">Main skin</a></li>
</ul>
</li>
<li><a class="MenuBarItemSubmenu get_free" title="Get it Free on Magenting.com" href="http://magenting.com">Get it Free on Magenting.com</a> </li>
<li class="bar_bt">&nbsp;</li>
</ul>
<script type="text/javascript">// <![CDATA[
var MenuBar5 = new Spry.Widget.MenuBar("MenuBar5");
// ]]></script>
</div></div>
                                </div>
                                <div class="col-right sidebar">
<div><div class="block block-popular">
        <div class="block-title">
        <strong><span>Most Popular</span></strong>
    </div>
    <div class="block-content">
        <ol class="mini-products-list" id="block-popular">
                    <li class="item">
                <div class="product">
                    <a href="http://web-experiment.info/magento14/bluescale/catalog/product/view/id/1384/s/hello-kitty-giant-face-lunchbox-by-loungefly/category/125/" title="Hello Kitty Giant Face Lunchbox " class="product-image"><img src="http://web-experiment.info/magento14/media/catalog/product/cache/17/thumbnail/50x/9df78eab33525d08d6e5fb8d27136e95/4/8/48958418ZPrORSIL.jpg" width="50" height="50" alt="Hello Kitty Giant Face Lunchbox "></a>
                    <div class="product-details">
                        <p class="product-name"><a href="http://web-experiment.info/magento14/bluescale/catalog/product/view/id/1384/s/hello-kitty-giant-face-lunchbox-by-loungefly/category/125/">Hello Kitty Giant Face Lunchbox </a></p>
                        

        
    <div class="price-box">
                                                            <span class="price-label">Our Price:</span>
                <span class="regular-price" id="product-price-1384-related">
                    <span class="price">$11.00</span>                </span>
                        
        </div>

                    </div>
                </div>
            </li>
                    <li class="item">
                <div class="product">
                    <a href="http://web-experiment.info/magento14/bluescale/catalog/product/view/id/1377/s/ty-beanie-baby-hello-kitty-chococat/category/125/" title="Ty Beanie Baby Hello Kitty Chococat" class="product-image"><img src="http://web-experiment.info/magento14/media/catalog/product/cache/17/thumbnail/50x/9df78eab33525d08d6e5fb8d27136e95/2/5/2598621WfKreOF8L.jpg" width="50" height="50" alt="Ty Beanie Baby Hello Kitty Chococat"></a>
                    <div class="product-details">
                        <p class="product-name"><a href="http://web-experiment.info/magento14/bluescale/catalog/product/view/id/1377/s/ty-beanie-baby-hello-kitty-chococat/category/125/">Ty Beanie Baby Hello Kitty Chococat</a></p>
                        

        
    <div class="price-box">
                                                            <span class="price-label">Our Price:</span>
                <span class="regular-price" id="product-price-1377-related">
                    <span class="price">$5.08</span>                </span>
                        
        </div>

                    </div>
                </div>
            </li>
                </ol>
</div>
</div>

</div></div>
                  				<?php
                  			}
                    if($this->matchedRoute != "publico-carrinho-compra" && $this->matchedRoute != "publico-finaliza-compra" && $this->matchedRoute != "publico-duvidas" && $this->matchedRoute != "publico-categoria/publico-categoria-e-subcategoria/publico-produto" && $this->matchedRoute != "publico-categoria/publico-categoria-e-subcategoria" && $this->matchedRoute != "publico-categoria")
                    {
                ?>
                <div class="col-left sidebar"><div><div class="block block-subscribe">
    <div class="block-title">
        <strong><span>Newsletter</span></strong>
    </div>
    <form action="http://web-experiment.info/magento14/bluescale/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <label for="newsletter">Sign up for our newsletter:</label>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email">
            </div>
            <div class="actions">
                <button type="submit" title="Subscribe" class="button"><span><span>Subscribe</span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
</div>
<div class="block">
<div class="block-title"><strong><span>Special Magento Hosting</span></strong></div>
<div class="block-content">
<p style="padding-left: 8px; padding-bottom: 0; margin-bottom: 0;"><strong><a title="Magento Hosting" href="http://magenting.com">Magento Hosting</a><br> with autoinstallation feature</strong> <br> <strong>Fast, Reliable, Secure</strong></p>
</div>
</div>
<div class="block block-download">
<div class="block-title"><strong><span>Download theme free</span></strong></div>
<div class="block-content">
<p><a class="download" title="Download Magento Theme Free" href="http://web-experiment.info/magento/media/downloads/webandpeople-magento-1.4-1.5-1.6.1.0-theme-bluescale-1.2.2.zip"><span>Download theme free</span></a></p>
</div>
</div>
<div>
<ul id="MenuBar5" class="MenuBarVertical buy_theme_left">
<li><a class="MenuBarItemSubmenu spec_th" title="Specials for this theme" href="javascript:;">Magento theme specials</a> 
<ul>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'gray']);" href="http://web-experiment.info/magento14/bluescale/bg_gray">Gray Background</a></li>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'white']);" href="http://web-experiment.info/magento14/bluescale/bg_white">White Background</a></li>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'flower']);" href="http://web-experiment.info/magento14/bluescale/bg_blue">Flower Background</a></li>
<li><a onclick="_gaq.push(['_trackEvent', 'navigation', 'bluescale', 'main']);" href="http://web-experiment.info/magento14/bluescale/">Main skin</a></li>
</ul>
</li>
<li><a class="MenuBarItemSubmenu get_free" title="Get it Free on Magenting.com" href="http://magenting.com">Get it Free on Magenting.com</a> </li>
<li class="bar_bt">&nbsp;</li>
</ul>
<script type="text/javascript">// <![CDATA[
var MenuBar5 = new Spry.Widget.MenuBar("MenuBar5");
// ]]></script>
</div><div class="block block-popular">
<div class="block-title"><strong><span>What's New</span></strong></div>
<div class="block-content">
<p style="text-align: center;"><a href="http://magenting.com" title="Professional Magento Hosting"><img src="http://web-experiment.info/magento14/media//promotion.jpg" alt="Professional Magento Hosting"></a></p>
</div>
</div></div>
<?php 
                    }
                    else if($this->matchedRoute == "publico-categoria/publico-categoria-e-subcategoria/publico-produto")
                    {
                    	?>
                    	<div class="col-right sidebar">
<div><div class="block block-popular">
        <div class="block-title">
        <strong><span style="font-size:10px;">Produtos Relacionados</span></strong>
    </div>
    <div class="block-content">
        <ol class="mini-products-list" id="block-popular">
                    <li class="item">
                <div class="product">
                    <a href="http://web-experiment.info/magento14/bluescale/hello-kitty-giant-face-lunchbox-by-loungefly.html" title="Hello Kitty Giant Face Lunchbox " class="product-image"><img src="http://web-experiment.info/magento14/media/catalog/product/cache/17/thumbnail/50x/9df78eab33525d08d6e5fb8d27136e95/4/8/48958418ZPrORSIL.jpg" width="50" height="50" alt="Hello Kitty Giant Face Lunchbox "></a>
                    <div class="product-details">
                        <p class="product-name"><a href="http://web-experiment.info/magento14/bluescale/hello-kitty-giant-face-lunchbox-by-loungefly.html">Hello Kitty Giant Face Lunchbox </a></p>
                        

        
    <div class="price-box">
                                                            <span class="price-label">Our Price:</span>
                <span class="regular-price" id="product-price-1384-related">
                    <span class="price">$11.00</span>                </span>
                        
        </div>

                    </div>
                </div>
            </li>
                    <li class="item">
                <div class="product">
                    <a href="http://web-experiment.info/magento14/bluescale/ty-beanie-baby-hello-kitty-chococat.html" title="Ty Beanie Baby Hello Kitty Chococat" class="product-image"><img src="http://web-experiment.info/magento14/media/catalog/product/cache/17/thumbnail/50x/9df78eab33525d08d6e5fb8d27136e95/2/5/2598621WfKreOF8L.jpg" width="50" height="50" alt="Ty Beanie Baby Hello Kitty Chococat"></a>
                    <div class="product-details">
                        <p class="product-name"><a href="http://web-experiment.info/magento14/bluescale/ty-beanie-baby-hello-kitty-chococat.html">Ty Beanie Baby Hello Kitty Chococat</a></p>
                        

        
    <div class="price-box">
                                                            <span class="price-label">Our Price:</span>
                <span class="regular-price" id="product-price-1377-related">
                    <span class="price">$5.08</span>                </span>
                        
        </div>

                    </div>
                </div>
            </li>
                </ol>
</div>
</div>

</div><div class="block block-viewed">
    <div class="block-title">
        <strong><span>Recently Viewed Products</span></strong>
    </div>
    <div class="block-content">
        <ol id="recently-viewed-items">
                    <li class="item odd">
                <p class="product-name"><a href="http://web-experiment.info/magento14/bluescale/ty-beanie-baby-hello-kitty-tartan.html">Ty Beanie Baby Hello Kitty Tartan</a></p>
            </li>
                    <li class="item last even">
                <p class="product-name"><a href="http://web-experiment.info/magento14/bluescale/diamonultratm-cubic-zirconia-platinum-over-sterling-silver-channel-set-ring.html">DiamonUltra™ Ring</a></p>
            </li>
                </ol>
        <script type="text/javascript">decorateList('recently-viewed-items');</script>
    </div>
</div>
</div>
                    	<?php 
                    }
                    ?>
            </div>
        </div>
         <div class="footer-container">
    <div class="footer">
        <div class="join_us_block"><a class="join" href="http://www.facebook.com/pages/WebAndPeople-Design-Studio/137511971195?ref=mf">Become a Fan on <strong>Facebook</strong></a><a class="join" href="http://twitter.com/webandpeople">Follow Us on<strong>Twitter</strong></a><a class="join" href="#">Join our <strong>Mailing List</strong></a></div><div class="footer_block">
<div class="links_block clearfix">
<div class="clearfix"><a class="title" href="#">Company Information</a> 
<ul>
<li><a href="#">About Us</a></li>
<li><a href="#">Our Store Hours</a></li>
<li><a href="#">Directions</a></li>
<li><a href="#">Privacy Policy</a></li>
<li><a href="#">Legal Information</a></li>
</ul>
</div>
<div><a class="title" href="#">Customer Service</a> 
<ul>
<li><a href="#">Ordering Information</a></li>
<li><a href="#">Delivery &amp; Rates</a></li>
<li><a href="#">Cancellations &amp; Returns</a></li>
<li><a href="#">School &amp; Government</a></li>
<li><a href="#">Contact Us</a></li>
</ul>
</div>
<div class="last"><a class="title" href="#">Useful Tips and Information</a> 
<ul>
<li><a href="#">Product Measurements</a></li>
<li><a href="#">Customer Testimonials</a></li>
<li><a href="#">Our Blog</a></li>
<li><a href="#">Site Map</a></li>
</ul>
</div>
</div>
</div>
<ul class="links">
            <li class="first" ><a href="http://web-experiment.info/magento14/bluescale/catalog/seo_sitemap/category/" title="Site Map" >Site Map</a></li>
            <li ><a href="http://web-experiment.info/magento14/bluescale/catalogsearch/term/popular/" title="Search Terms" >Search Terms</a></li>
            <li ><a href="http://web-experiment.info/magento14/bluescale/catalogsearch/advanced/" title="Advanced Search" >Advanced Search</a></li>
            <li class=" last" ><a href="http://web-experiment.info/magento14/bluescale/contacts/" title="Contact Us" >Contact Us</a></li>
    </ul>
<div class="design-by">
    Magento Themes by <a href="http://web-experiment.info">WebExperiment</a></div>
        <address>&copy; 2011 Your Company 
</address>
    </div>
</div>
            </div>
</div>

<script type="text/javascript">
<!--
var MenuBar2 = new Spry.Widget.MenuBar("MenuBar2");
var MenuBar3 = new Spry.Widget.MenuBar("MenuBar3");
//-->
</script>



</body>
</html>
        