<section class="pg-contato">

	<div id="form">
		<a href="" title="fechar"></a>
		<h2>INFORMAÇÕES</h2>		
		<p>Entre em contato com a Bout's através do formulário<br/> abaixo, este canal é exclusivo para consumidores.</p>

		<form method="post" action="#">

			<p><strong>Escolha o departamento:</strong></p>
			<br /><br />

		   <span class="check">
			<input class="sac" type="checkbox" name="opcao1" value="sac">
			<label class="sac" for="nome">SAC</label>
			
			<input class="marketing" type="checkbox" name="opcao2" value="Marketing">
			<label class="marketing" for="nome">Marketing</label> 
		   </span>

		   <span class="check-col">

		   	<label class="statusNome" for="nome">*Nome:</label>
			<input class="statusNome inputNome" type="text" name="nome" id="nome" />
			
			<label class="statusTelefone" for="nome">*Telefone:</label>
	        <input class="statusTelefone1 inputTelefoneDDD" type="text" name="nome" />
	        <input class="statusTelefone2 inputTelefoneNumero" type="text" name="nome" />  
	      
	        <label class="statusModelo" for="nome">*Modelo:</label>
			<input class="statusModelo InputModelo" type="text" name="nome" />

		   </span>

		   <span class="check-col">

		   	<label class="statusEmail" for="nome">*E-mail:</label>
			<input class="statusEmail InputEmail" type="text" name="nome"/> 
		
			<label for="nome" class="statusCidade">*Cidade:</label>
			<input class="statusCidade InputCidade" type="text"/>

			<label for="nome" class="statusUf">*UF:</label>
			<input class="statusUf InputUF" type="text"  style="width:20px;"/>
			
		   </span>
	                          
		   <label for="nome" class="statusMensagem">*Mensagem:</label>
		   <textarea name="mensagem" class="statusMensagem inputMensagem"></textarea>
		   <br class="clear" />
		   <button type="button" class="enviar EnviarContato" title="Enviar" id="save">Enviar</button>

	    </form>
	</div>
	
</section>