<header class="h-container">
	<section class="h-news">
        <div class="newsletter">
		<h5>Newsletter Bout’s</h5>
	    <p>Cadastre-se para receber notícias,<br/>
	    lançamento e ofertas.</p>
	    <input type="text" name="email" placeholder="Escreva seu endereço de e-mail"/>
		<button class="vd" type="submit" name="enviar" title="Cadastrar">Cadastrar</button>
		</div>
	</section>
</header>

<section class="galeria">
	<img src="img/galeria.jpg">
</section>

<section class="lancamentos">

	 <h2>lançamentos <span>Bout’s</span></h2>

	<!--<div class="swiper-container">
	    <div class="swiper-wrapper">

		      <div class="swiper-slide red-slide">
		        <div class="title">Slide 1</div>
		      </div>

		      <div class="swiper-slide blue-slide">
		        <div class="title">Slide 2</div>
		      </div>

		      <div class="swiper-slide orange-slide">
		        <div class="title">Slide 3</div>
		      </div>

		      <div class="swiper-slide green-slide">
		        <div class="title">Slide 4</div>
		      </div>

		      <div class="swiper-slide pink-slide">
		        <div class="title">Slide 5</div>
		      </div>

		      <div class="swiper-slide red-slide">
		        <div class="title">Slide 6</div>
		      </div>

		      <div class="swiper-slide blue-slide">
		        <div class="title">Slide 7</div>
		      </div>

		      <div class="swiper-slide orange-slide">
		        <div class="title">Slide 8</div>
		      </div>
	    </div>
  </div>-->
 

    <span><a class="s-esquerda" href=""></a></span>

	<div class="g-produtos swiper-container">
		
		<ul class="swiper-wrapper">
			<li class="swiper-slide">
				<a href="">
					<img src="img/tenis-teste.png">
					<h4>Glam</h4>
					<hr/>
					<p>tecnologia de amortecimento: <strong>Fly TS</strong></p>
				</a>
			</li>

			<li class="swiper-slide">
				<a href="">
					<img src="img/tenis-teste.png">
					<h4>Glam</h4>
					<hr/>
				    <p>tecnologia de amortecimento: <strong>Fly TS</strong></p>
				</a>
			</li>

			<li class="swiper-slide">
			  <a href="">
				<img src="img/tenis-teste.png">
				<h4>Glam</h4>
				<hr/>
				<p>tecnologia de amortecimento: <strong>Fly TS</strong></p>
			  </a>
		    </li>

		    <li class="swiper-slide">
			  <a href="">
				<img src="img/tenis-teste.png">
				<h4>Glam</h4>
				<hr/>
				<p>tecnologia de amortecimento: <strong>Fly TS</strong></p>
			  </a>
		    </li>

		    <li class="swiper-slide">
			  <a href="">
				<img src="img/tenis-teste.png">
				<h4>Glam</h4>
				<hr/>
				<p>tecnologia de amortecimento: <strong>Fly TS</strong></p>
			  </a>
		    </li>

		</ul>
	</div>

	<span><a class="s-direita" href=""></a></span>
    
</section>

<span class="linha-home">
	<img src="img/linha-home.jpg">
</span>

<section class="box-home">

	<div class="tec-bouts">

		<h3>Tecnologia Bout’s</h3>

		<ul>
			<li>
				<a href="">
					<p>Fly TS</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		    <li>
				<a href="">
					<p>Fly ts</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		    <li>
				<a href="">
					<p>Fly ts</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		    <li>
				<a href="">
					<p>Paulo Albertp</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		</ul>

	</div>
</section>
  <script src="js/jquery-1.10.1.min.js"></script>
  <script src="js/idangerous.swiper-2.1.min.js"></script>
  <script>
  var mySwiper = new Swiper('.swiper-container',{
    pagination: '.pagination',
    paginationClickable: true,
    slidesPerView: 3
  })
  </script>
