<header class="h-container">
		<section class="h-news">
            <div class="newsletter">
		    <h5>Newsletter Bout’s</h5>
			<p>Cadastre-se para receber notícias,<br/>
			lançamento e ofertas.</p>
			<input type="text" name="email" placeholder="Escreva seu endereço de e-mail"/>
			<button class="vd" type="submit" name="enviar" title="Cadastrar">Cadastrar</button>
		    </div>

		</section>

</header>


<section class="galeria">
	<img src="img/galeria.jpg">
</section>

<section class="lancamentos">
	lançamentos Bout’s
    <span><a class="s-esquerda" href=""></a></span>
	<div class="g-produtos">
		
		<ul>
			<li class="xxx">
				<a href="">
				</a>
			</li>
			<li><a href=""></a></li>
			<li><a href=""></a></li>
		</ul>
	</div>
	<span><a class="s-direita" href=""></a></span>
    
</section>
