<section id="home">

 			<header class="h-container">

		 		<section class="h-news">

		 			<div class="newsletter">

			 			<h5>Newsletter Bout’s</h5>

			 			<p>Cadastre-se para receber notícias,<br/>
			            lançamento e ofertas.</p>

			            <input type="text" name="email" placeholder="Escreva seu endereço de e-mail"/>

			            <button class="vd" type="submit" name="enviar" title="Cadastrar">Cadastrar</button>

		            </div>

		 		</section>

		 	</header>

 		</section>


 		<!--<h2>lançamentos <span>Bout’s</span></h2>



	    <div class="galeria">
			<ul>
				<li>
					<h4>Glam</h4>
                        <p>tecnologia de amortecimento: <span>Fly TS</span></p>
					<a href="">
					  <img src="img/tenis-teste.png">
					</a>
				</li>

				<li>
					<h4>Glam</h4>
                        <p>tecnologia de amortecimento: <span>Fly TS</span></p>
					<a href="">
					  <img src="img/tenis-teste.png">
					</a>
				</li>

				<li>
					<h4>Glam</h4>
                        <p>tecnologia de amortecimento: <span>Fly TS</span></p>
					<a href="">
					  <img src="img/tenis-teste.png">
					</a>
				</li>

			</ul>
		</div>

		<video>
			<iframe width="560" height="500" src="//www.youtube-nocookie.com/embed/iv9Gv_-VrL0" frameborder="0" allowfullscreen></iframe>
		</video>-->