<header class="h-container-top box-paralax">
	<section class="h-produtos">
		
		<h2>pratique Bout’s</h2>

		<div>

			<ul>
				<li><a class="dt-voltar" href="" title="Voltar">Voltar &nbsp;|</a></li>
				<li><a href="" title="Página Inicial">Página Inicial &nbsp;-</a></li>
				<li><a href="" title="Produtos">Mídia</a></li>
			</ul>

		</div>

	</section>
</header>


<section class="pg-midia">

	<div>
		<h3>Bout´s Training Pratique Bout´s</h3>

		<ul>
			<li class="video-principal">
				<iframe width="640" height="360" src="//www.youtube.com/embed/Qg_XOZvlMQU?rel=0" frameborder="0" allowfullscreen></iframe>
			</li>

			<li class="video-secundario">
				<iframe width="317" height="180" src="//www.youtube.com/embed/OBMBSH1gs6k?rel=0" frameborder="0" allowfullscreen></iframe>
				<figcaption>2007 - Bout's Spiral<br/>
					Comercial - Marcio Garcia</figcaption>
			</li>
			<li class="video-secundario">
				<iframe width="317" height="180" src="//www.youtube.com/embed/3dpy_p0JwSA?rel=0" frameborder="0" allowfullscreen></iframe>
				<figcaption>2008 - Tenis Bout's<br/>
					Comercial - Paparazzi</figcaption>
			</li>
			<li class="video-secundario">
				<iframe width="317" height="180" src="//www.youtube.com/embed/o8yboyCZI_k?rel=0" frameborder="0" allowfullscreen></iframe>
				<figcaption>2009 - Bouts Spiral X<br/>
					Versão Extendida</figcaption>
			</li>


			<li class="video-secundario">
				<iframe width="317" height="180" src="//www.youtube.com/embed/OBMBSH1gs6k?rel=0" frameborder="0" allowfullscreen></iframe>
				<figcaption>2007 - Bout's Spiral<br/>
					Comercial - Marcio Garcia</figcaption>
			</li>
			<li class="video-secundario">
				<iframe width="317" height="180" src="//www.youtube.com/embed/3dpy_p0JwSA?rel=0" frameborder="0" allowfullscreen></iframe>
				<figcaption>2008 - Tenis Bout's<br/>
					Comercial - Paparazzi</figcaption>
			</li>
			<li class="video-secundario">
				<iframe width="317" height="180" src="//www.youtube.com/embed/o8yboyCZI_k?rel=0" frameborder="0" allowfullscreen></iframe>
				<figcaption>2009 - Bouts Spiral X<br/>
					Versão Extendida</figcaption>
			</li>

		</ul>

	</div>

</section>