<section class="pg-midia">

	<div>
		<h3>Bout´s Training Pratique Bout´s</h3>

		<ul>
			<li class="video-principal">
				<object width="640" height="360" data="">
					<param name="movie" value="//www.youtube-nocookie.com/v/Qg_XOZvlMQU?version=3&amp;hl=pt_BR&amp;rel=0">
					<param name="allowFullScreen" value="true">
					<param name="allowscriptaccess" value="always">
					<embed src="//www.youtube-nocookie.com/v/Qg_XOZvlMQU?version=3&amp;hl=pt_BR&amp;rel=0" type="application/x-shockwave-flash" width="640" height="360" allowscriptaccess="always" allowfullscreen="true" wmode="transparent">
				</object>
			</li>

			<li class="video-secundario">
				<object width="317" height="180" data="">
					<param name="movie" value="//www.youtube-nocookie.com/v/OBMBSH1gs6k?version=3&amp;hl=pt_BR&amp;rel=0">
					<param name="allowFullScreen" value="true">
					<param name="allowscriptaccess" value="always">
				    <embed src="//www.youtube-nocookie.com/v/OBMBSH1gs6k?version=3&amp;hl=pt_BR&amp;rel=0" type="application/x-shockwave-flash" width="317" height="180" allowscriptaccess="always" allowfullscreen="true" wmode="transparent">
				</object>
				    <p>2007 - Bout's Spiral<br/>
					Comercial - Marcio Garcia</p>
			</li>

			<li class="video-secundario">
				<object width="317" height="180" data="">
					<param name="movie" value="//www.youtube-nocookie.com/v/3dpy_p0JwSA?version=3&amp;hl=pt_BR&amp;rel=0">
					<param name="allowFullScreen" value="true">
					<param name="allowscriptaccess" value="always">
					<embed src="//www.youtube-nocookie.com/v/3dpy_p0JwSA?version=3&amp;hl=pt_BR&amp;rel=0" type="application/x-shockwave-flash" width="317" height="180" allowscriptaccess="always" allowfullscreen="true" wmode="transparent">
				</object>
				<p>2008 - Tenis Bout's<br/>
					Comercial - Paparazzi</p>
			</li>

			<li class="video-secundario">
				<object width="317" height="180" data="">
					<param name="movie" value="//www.youtube-nocookie.com/v/o8yboyCZI_k?hl=pt_BR&amp;version=3&amp;rel=0">
					<param name="allowFullScreen" value="true">
					<param name="allowscriptaccess" value="always">
					<embed src="//www.youtube-nocookie.com/v/o8yboyCZI_k?hl=pt_BR&amp;version=3&amp;rel=0" type="application/x-shockwave-flash" width="317" height="180" allowscriptaccess="always" allowfullscreen="true" wmode="transparent">
				</object>
				<p>2009 - Bouts Spiral X<br/>
					Versão Extendida</p>
			</li>

		</ul>

	</div>

</section>