<section class="produto-detalhe">

	<div id="box-produtos">

		<div class="viewport-imagem">

		  <img width="650" alt="Destaque" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>big.png">

		</div>

		<div class="viewport">
		 <a class="previous" title="anterior" href=""></a>
			<div>
				<ul class="carouselPerspectiva">
					<li>
					 <a href="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>">
					  <img alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>medio.png">
					 </a>
					</li>
					<?php 
						foreach($this->produto->getPerspectiva() AS $perspectiva)
						{
					?>
					<li>
					 <a href="<?=$this->basePath()?>/img/produtos/<?=$perspectiva->getSrc()?>">
					  <img alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$perspectiva->getSrc()?>medio.png">
					 </a>
					</li>
					<?php 
						}
					?>
				</ul>
			</div>
		 <a class="next" title="próximo" href=""></a>
		</div>	

	</div>


	<div id="info-produtos">
		<h2>Tênis Bout’s <?=$this->produto->getTitulo()?></h2>

		<p class="txt-info"><?=$this->produto->getDescricao()?></p>
		<p class="txt-model">Modelo: <span class="valModel"><?=$this->produto->getNossoNumero()?></span></p>
		<p class="txt-tec">Tecnologia de amortecimento: <span class="dt-tec"><?=$this->produto->getBaseTecnologia()->getNome()?></span>
		</p>
		<p class="txt-number">Numeração: <span><?=$this->produto->getNumeracaoInicial()?> à <?=$this->produto->getNumeracaoFinal()?></span></p>

			<ul class="sugestaoTenis">
				
			<?php 
				foreach($this->produto->getSugestaoCoresProdutos() AS $produtoSugestao)
				{
			?>
				<li>
					<a href="#" rev="<?=$this->basePath()?>/img/produtos/<?=$produtoSugestao->getSrc()?>" rel="<?=$produtoSugestao->getNossoNumero()?>" class="eventOpenSugestao">
					<img rel="" alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$produtoSugestao->getSrc()?>medio.png">
					</a>
				</li>
<?php 
				}
			?>
				<li>
					<a href="<?=$this->url("produto/produto-subcategoria/produto-detalhe",array(
						"categoria" =>  $this->produto->getSubcategoriaTenis()->getCategoria()->getSlug(),
						"subcategoria" =>  $this->produto->getSubcategoriaTenis()->getSlug(),
						"slugProduto" => $this->produto->getSlug()	
					));?>" rel="<?=$this->produto->getNossoNumero()?>">
					<img alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>medio.png">
					</a>
				</li>
			</ul>

            <button type="button" class="share-face" title="Compartilhe no Facebook">Compartilhe no Facebook</button>

	</div>

</section>


