<section class="pg-produtos">

		<ul>
		<?php 
			foreach($this->produtos AS $produto)
			{
		?>
			<li>
				<img src="<?=$this->basePath()?>/img/produtos/<?=$produto->getSrc()?>">
				<a href="<?=$this->url("produto/produto-subcategoria/produto-detalhe",array(
					"categoria" => $produto->getSubcategoriaTenis()->getCategoria()->getSlug(),
					"subcategoria" => $produto->getSubcategoriaTenis()->getSlug(),
					"idProduto" => $produto->getIdtenis()		
				));?>" >
					<p><?=$produto->getModeloTenis()->getNome()?></p>
					<span></span>
					<p>veja mais</p>
			    </a>
		    </li>
		    <?php 
			}
		    ?>
		</ul>
</section>