<!--<header class="h-container-top">
	<section class="h-produtos">
		
		<h2>pratique Bout’s</h2>

		<div>

			<ul>
				<li><a class="dt-voltar" href="" title="Voltar">Voltar &nbsp;|</a></li>
				<li><a href="" title="Página Inicial">Página Inicial &nbsp;-</a></li>
				<li><a href="" title="Produtos">Produtos</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
				<li><a href="" title="Teste">Teste</a></li>
			</ul>

			<br/>

			<ul class="box-produto">
				<li><a class="tt-produto" href="" title="Calçados femininos">Calçados femininos &nbsp;-</a></li>
				<li><a href="" title="Step">Step</a></li>
			</ul>

		</div>

	</section>
</header>-->

<section class="pg-produtos">

		<ul>
		<?php 
			foreach($this->produtos AS $produto)
			{
		?>
			<li>
				<img src="<?=$this->basePath()?>/img/produtos/<?=$produto->getSrc()?>">
				<a href="<?=$this->url("produto/produto-subcategoria/produto-detalhe",array(
					"categoria" => $produto->getSubcategoriaTenis()->getCategoria()->getSlug(),
					"subcategoria" => $produto->getSubcategoriaTenis()->getSlug(),
					"idProduto" => $produto->getIdtenis()		
				));?>" >
					<p><?=$produto->getModeloTenis()->getNome()?></p>
					<span></span>
					<p>veja mais</p>
			    </a>
		    </li>
		    <?php 
			}
		    ?>
		</ul>
</section>