<section class="produto-detalhe">

	<div id="box-produtos">

		<div class="viewport-imagem">

		  <img title="teste" alt="teste" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>big.png">

		</div>

		<div class="viewport">
		 <a class="previous" title="anterior" href=""></a>
			<div>
				<ul>
					<li>
						<a href="">
							<img title="teste" alt="teste" width="115" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>medio.png">
						</a>
					</li>
				</ul>
			</div>
		 <a class="next" title="próximo" href=""></a>
		</div>	

	</div>


	<div id="info-produtos">
		<h2>Tênis Bout’s <?=$this->produto->getTitulo()?></h2>

		<p class="txt-info">Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, 
		e vem sendo utilizado desde o século XVI, quando um impressor esconhecido pegou uma bandeja de tipos.</p>
		<p class="txt-model">Modelo: <span>7207-340</span></p>
		<p class="txt-tec">Tecnologia de amortecimento <span class="dt-tec"><?=$this->produto->getBaseTecnologia()->getNome()?></span></p>
		<p class="txt-number">Numeração : <span><?=$this->produto->getNumeracaoInicial()?> à <?=$this->produto->getNumeracaoFinal()?></span></p>

			<ul>
				<li>
					<a href="">
					<img title="teste" alt="teste" src="<?=$this->basePath()?>/img/teste-viewport.png">
					</a>
				</li>

				<li>
					<a href="">
					<img title="teste" alt="teste" src="<?=$this->basePath()?>/img/teste-viewport.png">
					</a>
				</li>

				<li>
					<a href="">
					<img title="teste" alt="teste" src="<?=$this->basePath()?>/img/teste-viewport.png">
					</a>
				</li>

				<li>
					<a href="">
					<img title="teste" alt="teste" src="<?=$this->basePath()?>/img/teste-viewport.png">
					</a>
				</li>

				<li>
					<a href="">
					<img title="teste" alt="teste" src="<?=$this->basePath()?>/img/teste-viewport.png">
					</a>
				</li>

			</ul>
	</div>

</section>


