<?php 
$this->headMeta()->setProperty('og:locale', 'pt_BR');
$this->headMeta()->setProperty('og:url', $this->basePath());
$this->headMeta()->setProperty('og:title', $this->produto->getTitulo());
$this->headMeta()->setProperty('og:site_name', "Bout's sua vida em movimento");
$this->headMeta()->setProperty('og:image:type', "image/png");
$this->headMeta()->setProperty('og:image:width', 200);
$this->headMeta()->setProperty('og:image:height', 150);
$this->headMeta()->setProperty('og:description', $this->produto->getDescricao());
$this->headMeta()->setProperty('og:image', $this->basePath()."/img/produtos/".$this->produto->getSrc()."big.png");
?>

<section class="produto-detalhe">

	<div id="box-produtos">

		<div class="viewport-imagem">
		  <img width="650" class="zoomProduto" data-zoom-image="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>" alt="Destaque" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>big.png">
          <p class="av-mouse">Passe o mouse e veja detalhes</p>
		</div>

		<div class="viewport">
		 <a class="previous" title="anterior" href=""></a>
			<div>
				<ul class="carouselPerspectiva">
					<li>
					 <a href="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>">
					  <img alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>medio.png">
					 </a>
					</li>
					<?php 
						foreach($this->produto->getPerspectiva() AS $perspectiva)
						{
					?>
					<li>
					 <a href="<?=$this->basePath()?>/img/produtos/<?=$perspectiva->getSrc()?>">
					  <img alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$perspectiva->getSrc()?>medio.png">
					 </a>
					</li>
					<?php 
						}
					?>
				</ul>
			</div>
		 <a class="next" title="próximo" href=""></a>
		</div>	

	</div>


	<div id="info-produtos">
		<h2>Tênis Bout’s <?=$this->produto->getTitulo()?></h2>

		<p class="txt-info"><?=$this->produto->getDescricao()?></p>
		<p class="txt-model">Modelo: <span class="valModel"><?=$this->produto->getNossoNumero()?></span></p>
		<p class="txt-tec">Tecnologia de amortecimento: <span class="dt-tec" style="font-size: 0.9em"><?
		
			foreach($this->produto->getTecnologias() AS $tecnologia)
			{
				$tecs[] = '<a href="'.$this->url('tecnologia/tecnologia-detalhe',array("slug" => $tecnologia->getParenttecnologia()->getSlug())).'">'.$tecnologia->getParenttecnologia()->getNome()."</a>";
			}
			if(isset($tecs))
			{
			print implode(" + ", $tecs);	
			}
			?></span>
		</p>
		<p class="txt-number">Numeração: <span><?=$this->produto->getNumeracaoInicial()?> à <?=$this->produto->getNumeracaoFinal()?></span></p>

			<ul class="sugestaoTenis">
				
			<?php 
				foreach($this->produto->getSugestaoCoresProdutos() AS $produtoSugestao)
				{
			?>
				<li>
					<a href="#" rev="<?=$this->basePath()?>/img/produtos/<?=$produtoSugestao->getSrc()?>" rel="<?=$produtoSugestao->getNossoNumero()?>" class="eventOpenSugestao">
					<img rel="" alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$produtoSugestao->getSrc()?>medio.png">
					</a>
				</li>
<?php 
				}
			?>
				<li>
					<a href="<?=$this->url("produto/produto-subcategoria/produto-detalhe",array(
						"categoria" =>  $this->produto->getSubcategoriaTenis()->getCategoria()->getSlug(),
						"subcategoria" =>  $this->produto->getSubcategoriaTenis()->getSlug(),
						"slugProduto" => $this->produto->getSlug()	
					));?>" rel="<?=$this->produto->getNossoNumero()?>">
					<img alt="Produto" src="<?=$this->basePath()?>/img/produtos/<?=$this->produto->getSrc()?>medio.png">
					</a>
				</li>
			</ul>

            <!--<button type="button" class="share-face" title="Compartilhe no Facebook">Compartilhe no Facebook</button>-->

            <div id="fb-root"></div>
	        <script>(function(d, s, id) {
	          var js, fjs = d.getElementsByTagName(s)[0];
	          if (d.getElementById(id)) return;
	          js = d.createElement(s); js.id = id;
	          js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=643026039110903";
	          fjs.parentNode.insertBefore(js, fjs);
	        }(document, 'script', 'facebook-jssdk'));</script>

		    <div class="fb-share-button" data-href="<?=$this->url("produto/produto-subcategoria/produto-detalhe",array(
						"categoria" =>  $this->produto->getSubcategoriaTenis()->getCategoria()->getSlug(),
						"subcategoria" =>  $this->produto->getSubcategoriaTenis()->getSlug(),
						"slugProduto" => $this->produto->getSlug()	
					));?>" data-width="208" data-type="button">
		    </div>

	</div>

</section>


