<header class="h-container-top">
	<section class="h-produtos">
		
		<h2>pratique Bout’s</h2>

		<div>

			<ul>
				<li><a class="dt-voltar" href="" title="Voltar">Voltar &nbsp;|</a></li>
				<li><a href="" title="Página Inicial">Página Inicial &nbsp;-</a></li>
				<li><a href="" title="Produtos">Tecnologia</a></li>
			</ul>

			<br/>

			<ul class="box-produto">
				<li><a class="tt-produto" href="" title="Calçados femininos">Fly-ts</a></li>
			</ul>

		</div>

	</section>
</header>

<section class="pg-tecnologia">

	<!--<img src="<?=$this->basePath()?>/img/teste-tecnologia.png">-->

	<div class="pg-tec">

		<h3>Tecnologia de amortecimento fly ts </h3>

		<ul>
			<li class="flyts-01">
				<a href="">
					<p>Fly TS</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		    <li class="flyts-02">
				<a href="">
					<p>Fly ts</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		    <li class="flyts-03">
				<a href="">
					<p>Fly ts</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		    <li class="flyts-04">
				<a href="">
					<p>Paulo Albertp</p>
					<span></span>
					<p>saiba mais</p>
			    </a>
		    </li>

		</ul>

	</div>




</section>