<!--<header class="h-container-top box-paralax">
	<section class="h-produtos">
		
		<h2>pratique Bout’s</h2>

		<div>

			<ul>
				<li><a class="dt-voltar" href="" title="Voltar">Voltar &nbsp;|</a></li>
				<li><a href="" title="Página Inicial">Página Inicial &nbsp;-</a></li>
				<li><a href="" title="Produtos">Tecnologia</a></li>
			</ul>

			<br/>

			<ul class="box-produto">
				<li><a class="tt-produto" href="" title="Calçados femininos">Fly-ts</a></li>
			</ul>

		</div>

	</section>
</header>-->

<section class="pg-tecnologia"><!--<img src="<?=$this->basePath()?>/img/teste-tecnologia.png">-->

	    <div class="pg-galeria">
	    	<img src="<?=$this->basePath()?>/img/produtos/flyts-1-destaque.png">
		</div>

		<div class="pg-textos">
			<img src="<?=$this->basePath()?>/img/logo-flyTS.png">
			<p>A tecnologia Fly TS foi projetada, pensando em máxima proteção e conforto durante a pisada. É leve, resistente e com seus componentes tecnológicos como o tecido Mesh Dupla Frontura, laminados com alta capacidade de alongamento e flexão e palmilha em E.V.A, possui uma propriedade de ventilação absorvendo parte da umidade eventualmente gerada pela transpiração dos pés.<br/>
            Sistema de amortecimento composto por E.V.A injetado de alta resiliência, proporcionando melhor conforto para o uso no dia a dia e na prática de atividades físicas moderadas.</p>
		</div>

	<div class="pg-tec">

		<h3>Tecnologia de amortecimento fly ts </h3>

		<ul>
			<li class="flyts-01">
				<a href="" class="effect-top">
				  <img src="<?=$this->basePath()?>/img/lupa-tec.png">
			    </a>
		    </li>

		    <li class="flyts-02">
				<a href="" class="effect-left">
				   <img src="<?=$this->basePath()?>/img/lupa-tec.png">
			    </a>
		    </li>

		    <li class="flyts-03">
				<a href="" class="effect-bottom">
				<img src="<?=$this->basePath()?>/img/lupa-tec.png">
			    </a>
		    </li>

		    <li class="flyts-04">
				<a href="" class="effect-right">
				  <img src="<?=$this->basePath()?>/img/lupa-tec.png">
			    </a>
		    </li>

		</ul>

	</div>

</section>