<section class="pg-wallpaper">

	<img src="<?=$this->basePath()?>/img/teste-wallpaper.png">

	<ul>
		<li>
			<figure>
				<figcaption>Wallpaper</figcaption>
				<img src="<?=$this->basePath()?>/img/wallpaper1.jpg" title="Wallpaper" alt="Wallpaper">
			</figure>
			<span title="Download">
				<a href=""></a><br/>
				Download
			</span>
		</li>

		<li>
			<figure>
				<figcaption>Wallpaper</figcaption>
				<img src="<?=$this->basePath()?>/img/wallpaper1.jpg" title="Wallpaper" alt="Wallpaper">
			</figure>
			<span title="Download">
				<a href=""></a><br/>
				Download
			</span>
		</li>

		<li>
			<figure>
				<figcaption>Wallpaper</figcaption>
				<img src="<?=$this->basePath()?>/img/wallpaper1.jpg" title="Wallpaper" alt="Wallpaper">
			</figure>
			<span title="Download">
				<a href=""></a><br/>
				Download
			</span>
		</li>

		<li>
			<figure>
				<figcaption>Wallpaper</figcaption>
				<img src="<?=$this->basePath()?>/img/wallpaper1.jpg" title="Wallpaper" alt="Wallpaper">
			</figure>
			<span title="Download">
				<a href=""></a><br/>
				Download
			</span>
		</li>

		<li>
			<figure>
				<figcaption>Wallpaper</figcaption>
				<img src="<?=$this->basePath()?>/img/wallpaper1.jpg" title="Wallpaper" alt="Wallpaper">
			</figure>
			<span title="Download">
				<a href=""></a><br/>
				Download
			</span>
		</li>

		
	</ul>

</section>