<section class="pg-wallpaper">
	<ul>
	<?php 
		foreach($this->wallpaper->getFotos() AS $wallpaper)
		{
	?>
		<li>
			<figure>
				<p><?=$wallpaper->getTituloImagem()?></p>
				<img width="200" src="<?=$this->basePath("img/wallpapers/".$wallpaper->getSrc())?>" title="Wallpaper" alt="Wallpaper">
			</figure>
			<span title="Download">
				<a href="" title="Download"></a><br/>
				Download
			</span>
		</li>
		<?php 
		}
		?>
	</ul>
</section>

