<div id="gerenciar-persp">

	<ul>
		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>

		<li>
			<figure><img src="<?=$this->basePath()?>/img/produtos/load_53ab3c6e0cda6.pngbig.png"></figure>
			<button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="">Excluir</button>
		</li>
	</ul>

</div>