<?php 
		foreach($this->listaSubcategorias AS $subcategoria)
		{
			?>
			<option value="<?=$subcategoria->getIdsubcategoria()?>" <?if($this->checked == $subcategoria->getIdsubcategoria()) print 'selected';?>><?=$subcategoria->getNome()?></option>
			<?php
		}
?>
<?php 
	if(count($this->listaSubcategorias) >= 1)
	{
?>
<option value="adicionaOutra">Adicionar Sub-Categoria</option>
<?php 
	}
?>