<div style="display: none;font-size:12px;" id="popupCor">
	<form class="formpopupCor">
    <input type="text" class="modelo" placeholder="Digite o modelo do tênis"/><br/>
	<input type="file" class="arquivo" /><br/><br/>
	</form>
</div>
<form class="formProduto">
    <input type="text" class="titulo" placeholder="Nome do Tênis"/><br/>
    <textarea name="mensagem" class="statusDescricaoTenis" placeholder="Uma breve descrição do tênis"></textarea><br/>
    <input type="text" class="modelo" placeholder="Digite o modelo do tênis"/><br/>
    <label class="numeracao" for="" style="cursor:default; color:#222; font-size:14px;"><strong>Numeração do Tênis</strong></label>
    <input type="text" class="style-tamanho tamanhoMin" placeholder="Minímo"/> 
    <input type="text" class="style-tamanho tamanhoMax" placeholder="Máximo"/>
    <br/>
    <label class="numeracao" for="" style="cursor:default; color:#222; font-size:14px;"><strong>Selecione Tecnologia de Amortecimento</strong></label>
    <?php 
         	foreach($this->tecnologia->getSubmenus() AS $tecnologia)
         	{
         		?>
    <input class="tecnologia" type="checkbox" value="<?=$tecnologia->getIdbaseSubmenu()?>"><?=$tecnologia->getNome()?><br>
    <?php 
         	}
    ?>
    <br/>
	<div class="categoriaSelect">
	<select  class="form-control categoria">
         <option value="">Selecione uma Categoria</option>
         <?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
         		<option value="<?=$categoria->getIdcategoria()?>"><?=$categoria->getNome()?></option>
         		<?php 
         	}
         ?>
         <option value="addCategoria">Adicionar Categoria</option>
	</select><br/>
	</div>
	<div style="display:none" class="adicionaCategoria">
		<input type="text" class="tituloCategoria" placeholder="Titulo da categoria"/> <input type="submit" class="salvarCategoriaProduto" value="Salvar Categoria" title="Salvar"> 
	</div>
	<div style="display:none" class="adicionaSubCategoria">
		<input type="text" class="tituloSubCategoria" placeholder="Titulo da Sub-Categoria"/><input type="submit" class="salvarSubCategoriaProduto" value="Salvar Sub-Categoria" title="Salvar"> 
	</div>
	<div class="subcategoriaSelect">
	<select  class="form-control subcategoria" disabled="disabled">
      <option value="">Selecione uma Subcategoria</option>
	</select><br/>
	</div>
	<input type="file" class="arquivo" /><br/><br/>
    <label class="add-vitrine" for="" style="cursor:default; color:#222; font-size:14px;"><strong>Adicionar produto na Vitrine</strong></label>
    <input class="vitrine" type="radio" name="gender" value="sim"> Sim
    <input class="vitrine" type="radio" name="gender" value="nao" checked="checked"> Não<br/>
    <div style="display:none" class="fotoAdicionalVitrine">
    <input type="file" class="fotoVitrine" />
    </div>
    <br/><br/>
	<input type="submit" value="Adicionar" class="actionAdicionaProduto style-adicionar" title="Adicionar Produto"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Produto"><br/>
</form>

    <span class="g-categorias">
        <h5>Gerenciar Categorias:</h5>
        <ul class="box-produto">
        <?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
            <li class="tt-produto"><strong><?=$categoria->getNome()?></strong><a rel="<?=$categoria->getIdcategoria()?>" class="tt-produto excluirCategoria" href="" title="excluir">Excluir</a>
                <a rel="<?=$categoria->getIdcategoria()?>" class="edit-categoria" href="" title="editar categoria" rel="<?=$categoria->getIdcategoria()?>">editar</a>
                <div id="box-editar" class="boxCategoria<?=$categoria->getIdcategoria()?>" style="display:none">
                    <input type="text" placeholder="<?=$categoria->getNome()?>" class="valorSet"/>
                    <a rel="<?=$categoria->getIdcategoria()?>" class="edit-confirma actionEditarCategoria" href="" title="confirmar edição">Confirmar</a>
                </div>

                <ul>
                <?php 
                	foreach($categoria->getSubcategorias() AS $subcategoria)
                	{
                ?>
                    <li><?=$subcategoria->getNome()?><a href="" rel="<?=$subcategoria->getIdsubcategoria()?>" title="excluir" class="ex-sub excluirSubcategoria">Excluir</a>
                        <a class="edit-subcategoria"  rel="<?=$subcategoria->getIdsubcategoria()?>" href="" title="editar sub-categoria">editar</a>
                        <div id="box-editar" style="display:none" class="boxCategoriaSubcategoria<?=$subcategoria->getIdsubcategoria()?>">
                            <input type="text"placeholder="<?=$subcategoria->getNome()?>" class="valorSet"/>
                            <a rel="<?=$subcategoria->getIdsubcategoria()?>" class="edit-confirma actionEditarCategoriaSub" href="" title="confirmar edição">Confirmar</a>
                        </div>
                    </li>
                    <?php 
                	}
                    ?>
                </ul>
            </li>
            <?php 
         	}
            ?>
        </ul>
    </span>

<div class="accordion" id="accordion2">
    <p>Gerenciar Categorias</p>
<?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?=$categoria->getIdcategoria()?>">
     	<?=strtoupper($categoria->getNome())?>
      </a>
    </div>

    <div id="collapse<?=$categoria->getIdcategoria()?>" class="accordion-body collapse">

      <div class="accordion-inner">
        <ul class="accordion-produto">
		        <?php 
		        	foreach($categoria->getSubcategorias() AS $sub)
		        	{
		        		foreach($sub->getProdutos() AS $produto)
		        		{
		        ?>
		         <li>
		            <img src="<?=$this->basePath()?>/img/produtos/<?=$produto->getSrc()?>">
		            <p><?=$produto->getTitulo()?></p>
		            <p><strong>Modelo:</strong> <?=$produto->getNossoNumero()?></p>
		            <button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="<?=$produto->getIdtenis()?>">Excluir</button>
                    <button type="button" class="btn btn-info AddCor" title="Adicionar uma nova cor" rev="produtos" rel="<?=$produto->getIdtenis()?>">Nova Cor</button>

		         </li>
		         			<?php 
		         			if($produto->getSugestaoCoresProdutos())
		         			{
		         				foreach($produto->getSugestaoCoresProdutos() AS $produtoSugestao)
		         				{
		         					?>
		         					 <li style="border:solid red 1px">
							            <img src="<?=$this->basePath()?>/img/produtos/<?=$produtoSugestao->getSrc()?>">
							            <p><?=$produto->getTitulo()?></p>
							            <p><strong>Modelo:</strong> <?=$produtoSugestao->getNossoNumero()?></p>
							            <button type="button" class="btn btn-danger deletarSugestaoAction" title="excluir item " rev="produtos" rel="<?=$produtoSugestao->getIdSugestaoCores()?>">Excluir</button>
							         </li>
		         					<?php
		         				}
		         			}	
		         			?>
		         <?php 
		        		}
		        	}
		         ?>
        </ul>
      </div>
    </div>
  </div>
<?php 	
         	}	
?>
</div>
