<form class="formProduto">
    <input type="text" class="titulo" placeholder="Nome do Tênis"/><br/>

    <textarea name="mensagem" class="statusDescricaoTenis" placeholder="Uma breve descrição do tênis"></textarea><br/>

    <input type="text" class="modelo" placeholder="Digite o modelo do tênis"/><br/>

    <label class="numeracao" for="" style="cursor:default; color:#222; font-size:14px;"><strong>Numeração do Tênis</strong></label>
    <input type="text" class="style-tamanho tamanhoMin" placeholder="Minímo"/> 
    <input type="text" class="style-tamanho tamanhoMax" placeholder="Máximo"/>
    <br/>

    <select  class="form-control tecnologia" style="width:300px;" <?if(!$this->tecnologia) print 'disabled="disabled"'?>>
         <option value="">Selecione Tecnologia de Amortecimento</option>
         <?php 
         	foreach($this->tecnologia->getSubmenus() AS $tecnologia)
         	{
         		?>
         		<option value="<?=$tecnologia->getIdbaseSubmenu()?>"><?=$tecnologia->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>

	<select  class="form-control categoria" <?if(!$this->categorias) print 'disabled="disabled"'?>>
         <option value="">Selecione uma Categoria</option>
         <?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
         		<option value="<?=$categoria->getIdcategoria()?>"><?=$categoria->getNome()?></option>
         		<?php 
         	}
         ?>
	</select><br/>

	<select  class="form-control subcategoria" disabled="disabled">
      <option value="">Selecione uma Subcategoria</option>
	</select><br/>
	<input type="file" class="arquivo" /><br/><br/>
	
    <label class="add-vitrine" for="" style="cursor:default; color:#222; font-size:14px;"><strong>Adicionar produto na Vitrine</strong></label>
    <input class="vitrine" type="radio" name="gender" value="sim"> Sim
    <input class="vitrine" type="radio" name="gender" value="nao" checked="checked"> Não<br/>
    <Div style="display:none" class="fotoAdicionalVitrine">
    <input type="file" class="fotoVitrine" />
    </Div>
    <br/><br/>



	<input type="submit" value="Adicionar" class="actionAdicionaProduto style-adicionar" title="Adicionar Banner"> 
	<input type="submit" value="Gerenciar" class="style-gerenciar" title="Gerenciar Banner"><br/>


</form>


<div class="accordion" id="accordion2">
    <p>Gerenciar Categorias</p>
<?php 
         	foreach($this->categorias AS $categoria)
         	{
         		?>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?=$categoria->getIdcategoria()?>">
     	<?=strtoupper($categoria->getNome())?>
      </a>
    </div>

    <div id="collapse<?=$categoria->getIdcategoria()?>" class="accordion-body collapse">

      <div class="accordion-inner">
        <ul class="accordion-produto">
		        <?php 
		        	foreach($categoria->getSubcategorias() AS $sub)
		        	{
		        		foreach($sub->getProdutos() AS $produto)
		        		{
		        ?>
		         <li>
		            <img src="<?=$this->basePath()?>/img/produtos/<?=$produto->getSrc()?>">
		            <p><strong>Tênis:</strong> <?=$produto->getTitulo()?></p>
		            <p><strong>Modelo:</strong> <?=$produto->getNossoNumero()?></p>
		            <button type="button" class="btn btn-danger deletarAction" title="excluir item " rev="produtos" rel="<?=$produto->getIdtenis()?>">Excluir</button>
		         </li>
		         <?php 
		        		}
		        	}
		         ?>
        </ul>
      </div>
    </div>
  </div>
<?php 	
         	}	
?>
</div>