
<div id="adm-popup">
	<p>
		<h4></h4>
		<conteudo class="conteudo">dsa</conteudo>
	</p>
</div>
	<a href="" title="Gerenciamento de Banners:" class="openPopup" rel="banner"><img src="<?=$this->basepath("img/btn_banner.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Banners:" class="openPopup" rel="midia"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Banners:" class="openPopup" rel="ondeComprar"><img src="<?=$this->basepath("img/btn_onde-comprarr.png")?>" class="img-polaroid" width="300"></a>
    <a href="" title="Gerenciamento de Banners:" class="openPopup" rel="produtos"><img src="<?=$this->basepath("img/btn_produtos.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Banners:" class="openPopup" rel="tecnologia"><img src="<?=$this->basepath("img/btn_tecnologia.png")?>" class="img-polaroid" width="300"></a>
    <a href=""  title="Gerenciamento de Banners:" class="openPopup" rel="wallpaper"><img src="<?=$this->basepath("img/btn_wallpaper.png")?>" class="img-polaroid" width="300"></a>
    