<style>
	#adm-popup{
		display:none;
		background-color:cinze;
		border:1px solid rgba(0,0,0,0.2);
		margin: 5px 0px 5px 0px;
		padding:5px;
	}
	#adm-popup h4{
		color:#778899
	}
</style>
<div id="adm-popup">
	<p>
		<h4></h4>
		<conteudo class="conteudo">dsa</conteudo>
	</p>
</div>
	<a href="" title="Gerenciamento de Banners:" class="openPopup" rel="banner"><img src="<?=$this->basepath("img/btn_banner.png")?>" class="img-polaroid" width="300"></a>
    <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_midia.png")?>" class="img-polaroid" width="300"></a>
    <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_onde-comprarr.png")?>" class="img-polaroid" width="300"></a>
    <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_produtos.png")?>" class="img-polaroid" width="300"></a>
    <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_tecnologia.png")?>" class="img-polaroid" width="300"></a>
    <a href="" class="openPopup"><img src="<?=$this->basepath("img/btn_wallpaper.png")?>" class="img-polaroid" width="300"></a>
    